/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package io.jetprocess.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the BasicHead service. Represents a row in the &quot;JP_BasicHead&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>io.jetprocess.model.impl.BasicHeadModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>io.jetprocess.model.impl.BasicHeadImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BasicHead
 * @generated
 */
@ProviderType
public interface BasicHeadModel extends BaseModel<BasicHead> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a basic head model instance should use the {@link BasicHead} interface instead.
	 */

	/**
	 * Returns the primary key of this basic head.
	 *
	 * @return the primary key of this basic head
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this basic head.
	 *
	 * @param primaryKey the primary key of this basic head
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the basic head ID of this basic head.
	 *
	 * @return the basic head ID of this basic head
	 */
	public long getBasicHeadId();

	/**
	 * Sets the basic head ID of this basic head.
	 *
	 * @param basicHeadId the basic head ID of this basic head
	 */
	public void setBasicHeadId(long basicHeadId);

	/**
	 * Returns the basic head value of this basic head.
	 *
	 * @return the basic head value of this basic head
	 */
	@AutoEscape
	public String getBasicHeadValue();

	/**
	 * Sets the basic head value of this basic head.
	 *
	 * @param basicHeadValue the basic head value of this basic head
	 */
	public void setBasicHeadValue(String basicHeadValue);

	/**
	 * Returns the basic head code of this basic head.
	 *
	 * @return the basic head code of this basic head
	 */
	public long getBasicHeadCode();

	/**
	 * Sets the basic head code of this basic head.
	 *
	 * @param basicHeadCode the basic head code of this basic head
	 */
	public void setBasicHeadCode(long basicHeadCode);

	@Override
	public BasicHead cloneWithOriginalValues();

}