/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package io.jetprocess.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Dispatch service. Represents a row in the &quot;JP_Dispatch&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>io.jetprocess.model.impl.DispatchModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>io.jetprocess.model.impl.DispatchImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Dispatch
 * @generated
 */
@ProviderType
public interface DispatchModel
	extends BaseModel<Dispatch>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dispatch model instance should use the {@link Dispatch} interface instead.
	 */

	/**
	 * Returns the primary key of this dispatch.
	 *
	 * @return the primary key of this dispatch
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dispatch.
	 *
	 * @param primaryKey the primary key of this dispatch
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this dispatch.
	 *
	 * @return the uuid of this dispatch
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this dispatch.
	 *
	 * @param uuid the uuid of this dispatch
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this dispatch.
	 *
	 * @return the ID of this dispatch
	 */
	public long getId();

	/**
	 * Sets the ID of this dispatch.
	 *
	 * @param id the ID of this dispatch
	 */
	public void setId(long id);

	/**
	 * Returns the group ID of this dispatch.
	 *
	 * @return the group ID of this dispatch
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this dispatch.
	 *
	 * @param groupId the group ID of this dispatch
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this dispatch.
	 *
	 * @return the company ID of this dispatch
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this dispatch.
	 *
	 * @param companyId the company ID of this dispatch
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this dispatch.
	 *
	 * @return the user ID of this dispatch
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this dispatch.
	 *
	 * @param userId the user ID of this dispatch
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this dispatch.
	 *
	 * @return the user uuid of this dispatch
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this dispatch.
	 *
	 * @param userUuid the user uuid of this dispatch
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this dispatch.
	 *
	 * @return the user name of this dispatch
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this dispatch.
	 *
	 * @param userName the user name of this dispatch
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this dispatch.
	 *
	 * @return the create date of this dispatch
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this dispatch.
	 *
	 * @param createDate the create date of this dispatch
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this dispatch.
	 *
	 * @return the modified date of this dispatch
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this dispatch.
	 *
	 * @param modifiedDate the modified date of this dispatch
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the dispatch no of this dispatch.
	 *
	 * @return the dispatch no of this dispatch
	 */
	@AutoEscape
	public String getDispatchNo();

	/**
	 * Sets the dispatch no of this dispatch.
	 *
	 * @param dispatchNo the dispatch no of this dispatch
	 */
	public void setDispatchNo(String dispatchNo);

	/**
	 * Returns the dispatch by of this dispatch.
	 *
	 * @return the dispatch by of this dispatch
	 */
	@AutoEscape
	public String getDispatchBy();

	/**
	 * Sets the dispatch by of this dispatch.
	 *
	 * @param dispatchBy the dispatch by of this dispatch
	 */
	public void setDispatchBy(String dispatchBy);

	/**
	 * Returns the delivery mode of this dispatch.
	 *
	 * @return the delivery mode of this dispatch
	 */
	@AutoEscape
	public String getDeliveryMode();

	/**
	 * Sets the delivery mode of this dispatch.
	 *
	 * @param deliveryMode the delivery mode of this dispatch
	 */
	public void setDeliveryMode(String deliveryMode);

	/**
	 * Returns the address of this dispatch.
	 *
	 * @return the address of this dispatch
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this dispatch.
	 *
	 * @param address the address of this dispatch
	 */
	public void setAddress(String address);

	/**
	 * Returns the subject of this dispatch.
	 *
	 * @return the subject of this dispatch
	 */
	@AutoEscape
	public String getSubject();

	/**
	 * Sets the subject of this dispatch.
	 *
	 * @param subject the subject of this dispatch
	 */
	public void setSubject(String subject);

	/**
	 * Returns the dispath on of this dispatch.
	 *
	 * @return the dispath on of this dispatch
	 */
	@AutoEscape
	public String getDispathOn();

	/**
	 * Sets the dispath on of this dispatch.
	 *
	 * @param dispathOn the dispath on of this dispatch
	 */
	public void setDispathOn(String dispathOn);

	/**
	 * Returns the dispatch type of this dispatch.
	 *
	 * @return the dispatch type of this dispatch
	 */
	@AutoEscape
	public String getDispatchType();

	/**
	 * Sets the dispatch type of this dispatch.
	 *
	 * @param dispatchType the dispatch type of this dispatch
	 */
	public void setDispatchType(String dispatchType);

	/**
	 * Returns the issue no of this dispatch.
	 *
	 * @return the issue no of this dispatch
	 */
	@AutoEscape
	public String getIssueNo();

	/**
	 * Sets the issue no of this dispatch.
	 *
	 * @param issueNo the issue no of this dispatch
	 */
	public void setIssueNo(String issueNo);

	/**
	 * Returns the receiptent ID of this dispatch.
	 *
	 * @return the receiptent ID of this dispatch
	 */
	public long getReceiptentId();

	/**
	 * Sets the receiptent ID of this dispatch.
	 *
	 * @param receiptentId the receiptent ID of this dispatch
	 */
	public void setReceiptentId(long receiptentId);

	/**
	 * Returns the draft ID of this dispatch.
	 *
	 * @return the draft ID of this dispatch
	 */
	public long getDraftId();

	/**
	 * Sets the draft ID of this dispatch.
	 *
	 * @param draftId the draft ID of this dispatch
	 */
	public void setDraftId(long draftId);

	@Override
	public Dispatch cloneWithOriginalValues();

}