/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package io.jetprocess.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DocumentNoteMapping service. Represents a row in the &quot;JP_DocumentNoteMapping&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>io.jetprocess.model.impl.DocumentNoteMappingModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>io.jetprocess.model.impl.DocumentNoteMappingImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DocumentNoteMapping
 * @generated
 */
@ProviderType
public interface DocumentNoteMappingModel
	extends BaseModel<DocumentNoteMapping>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a document note mapping model instance should use the {@link DocumentNoteMapping} interface instead.
	 */

	/**
	 * Returns the primary key of this document note mapping.
	 *
	 * @return the primary key of this document note mapping
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this document note mapping.
	 *
	 * @param primaryKey the primary key of this document note mapping
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this document note mapping.
	 *
	 * @return the uuid of this document note mapping
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this document note mapping.
	 *
	 * @param uuid the uuid of this document note mapping
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this document note mapping.
	 *
	 * @return the ID of this document note mapping
	 */
	public long getId();

	/**
	 * Sets the ID of this document note mapping.
	 *
	 * @param id the ID of this document note mapping
	 */
	public void setId(long id);

	/**
	 * Returns the group ID of this document note mapping.
	 *
	 * @return the group ID of this document note mapping
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this document note mapping.
	 *
	 * @param groupId the group ID of this document note mapping
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this document note mapping.
	 *
	 * @return the company ID of this document note mapping
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this document note mapping.
	 *
	 * @param companyId the company ID of this document note mapping
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this document note mapping.
	 *
	 * @return the user ID of this document note mapping
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this document note mapping.
	 *
	 * @param userId the user ID of this document note mapping
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this document note mapping.
	 *
	 * @return the user uuid of this document note mapping
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this document note mapping.
	 *
	 * @param userUuid the user uuid of this document note mapping
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this document note mapping.
	 *
	 * @return the user name of this document note mapping
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this document note mapping.
	 *
	 * @param userName the user name of this document note mapping
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this document note mapping.
	 *
	 * @return the create date of this document note mapping
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this document note mapping.
	 *
	 * @param createDate the create date of this document note mapping
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this document note mapping.
	 *
	 * @return the modified date of this document note mapping
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this document note mapping.
	 *
	 * @param modifiedDate the modified date of this document note mapping
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the note document ID of this document note mapping.
	 *
	 * @return the note document ID of this document note mapping
	 */
	public long getNoteDocumentId();

	/**
	 * Sets the note document ID of this document note mapping.
	 *
	 * @param noteDocumentId the note document ID of this document note mapping
	 */
	public void setNoteDocumentId(long noteDocumentId);

	/**
	 * Returns the note ID of this document note mapping.
	 *
	 * @return the note ID of this document note mapping
	 */
	public long getNoteId();

	/**
	 * Sets the note ID of this document note mapping.
	 *
	 * @param noteId the note ID of this document note mapping
	 */
	public void setNoteId(long noteId);

	@Override
	public DocumentNoteMapping cloneWithOriginalValues();

}