/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package io.jetprocess.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DraftRecipient service. Represents a row in the &quot;JP_DraftRecipient&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>io.jetprocess.model.impl.DraftRecipientModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>io.jetprocess.model.impl.DraftRecipientImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DraftRecipient
 * @generated
 */
@ProviderType
public interface DraftRecipientModel
	extends BaseModel<DraftRecipient>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a draft recipient model instance should use the {@link DraftRecipient} interface instead.
	 */

	/**
	 * Returns the primary key of this draft recipient.
	 *
	 * @return the primary key of this draft recipient
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this draft recipient.
	 *
	 * @param primaryKey the primary key of this draft recipient
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this draft recipient.
	 *
	 * @return the uuid of this draft recipient
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this draft recipient.
	 *
	 * @param uuid the uuid of this draft recipient
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this draft recipient.
	 *
	 * @return the ID of this draft recipient
	 */
	public long getId();

	/**
	 * Sets the ID of this draft recipient.
	 *
	 * @param id the ID of this draft recipient
	 */
	public void setId(long id);

	/**
	 * Returns the group ID of this draft recipient.
	 *
	 * @return the group ID of this draft recipient
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this draft recipient.
	 *
	 * @param groupId the group ID of this draft recipient
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this draft recipient.
	 *
	 * @return the company ID of this draft recipient
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this draft recipient.
	 *
	 * @param companyId the company ID of this draft recipient
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this draft recipient.
	 *
	 * @return the user ID of this draft recipient
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this draft recipient.
	 *
	 * @param userId the user ID of this draft recipient
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this draft recipient.
	 *
	 * @return the user uuid of this draft recipient
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this draft recipient.
	 *
	 * @param userUuid the user uuid of this draft recipient
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this draft recipient.
	 *
	 * @return the user name of this draft recipient
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this draft recipient.
	 *
	 * @param userName the user name of this draft recipient
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this draft recipient.
	 *
	 * @return the create date of this draft recipient
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this draft recipient.
	 *
	 * @param createDate the create date of this draft recipient
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this draft recipient.
	 *
	 * @return the modified date of this draft recipient
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this draft recipient.
	 *
	 * @param modifiedDate the modified date of this draft recipient
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the draft ID of this draft recipient.
	 *
	 * @return the draft ID of this draft recipient
	 */
	public long getDraftId();

	/**
	 * Sets the draft ID of this draft recipient.
	 *
	 * @param draftId the draft ID of this draft recipient
	 */
	public void setDraftId(long draftId);

	/**
	 * Returns the organization ID of this draft recipient.
	 *
	 * @return the organization ID of this draft recipient
	 */
	public long getOrganizationId();

	/**
	 * Sets the organization ID of this draft recipient.
	 *
	 * @param organizationId the organization ID of this draft recipient
	 */
	public void setOrganizationId(long organizationId);

	/**
	 * Returns the name of this draft recipient.
	 *
	 * @return the name of this draft recipient
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this draft recipient.
	 *
	 * @param name the name of this draft recipient
	 */
	public void setName(String name);

	/**
	 * Returns the designation of this draft recipient.
	 *
	 * @return the designation of this draft recipient
	 */
	@AutoEscape
	public String getDesignation();

	/**
	 * Sets the designation of this draft recipient.
	 *
	 * @param designation the designation of this draft recipient
	 */
	public void setDesignation(String designation);

	/**
	 * Returns the email of this draft recipient.
	 *
	 * @return the email of this draft recipient
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this draft recipient.
	 *
	 * @param email the email of this draft recipient
	 */
	public void setEmail(String email);

	/**
	 * Returns the mobile of this draft recipient.
	 *
	 * @return the mobile of this draft recipient
	 */
	@AutoEscape
	public String getMobile();

	/**
	 * Sets the mobile of this draft recipient.
	 *
	 * @param mobile the mobile of this draft recipient
	 */
	public void setMobile(String mobile);

	/**
	 * Returns the address of this draft recipient.
	 *
	 * @return the address of this draft recipient
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this draft recipient.
	 *
	 * @param address the address of this draft recipient
	 */
	public void setAddress(String address);

	/**
	 * Returns the state ID of this draft recipient.
	 *
	 * @return the state ID of this draft recipient
	 */
	public long getStateId();

	/**
	 * Sets the state ID of this draft recipient.
	 *
	 * @param stateId the state ID of this draft recipient
	 */
	public void setStateId(long stateId);

	/**
	 * Returns the city ID of this draft recipient.
	 *
	 * @return the city ID of this draft recipient
	 */
	@AutoEscape
	public String getCityId();

	/**
	 * Sets the city ID of this draft recipient.
	 *
	 * @param cityId the city ID of this draft recipient
	 */
	public void setCityId(String cityId);

	/**
	 * Returns the pin code of this draft recipient.
	 *
	 * @return the pin code of this draft recipient
	 */
	@AutoEscape
	public String getPinCode();

	/**
	 * Sets the pin code of this draft recipient.
	 *
	 * @param pinCode the pin code of this draft recipient
	 */
	public void setPinCode(String pinCode);

	@Override
	public DraftRecipient cloneWithOriginalValues();

}