/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package io.jetprocess.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Postal service. Represents a row in the &quot;JP_Postal&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>io.jetprocess.model.impl.PostalModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>io.jetprocess.model.impl.PostalImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Postal
 * @generated
 */
@ProviderType
public interface PostalModel
	extends BaseModel<Postal>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a postal model instance should use the {@link Postal} interface instead.
	 */

	/**
	 * Returns the primary key of this postal.
	 *
	 * @return the primary key of this postal
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this postal.
	 *
	 * @param primaryKey the primary key of this postal
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this postal.
	 *
	 * @return the uuid of this postal
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this postal.
	 *
	 * @param uuid the uuid of this postal
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this postal.
	 *
	 * @return the ID of this postal
	 */
	public long getId();

	/**
	 * Sets the ID of this postal.
	 *
	 * @param id the ID of this postal
	 */
	public void setId(long id);

	/**
	 * Returns the group ID of this postal.
	 *
	 * @return the group ID of this postal
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this postal.
	 *
	 * @param groupId the group ID of this postal
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this postal.
	 *
	 * @return the company ID of this postal
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this postal.
	 *
	 * @param companyId the company ID of this postal
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this postal.
	 *
	 * @return the user ID of this postal
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this postal.
	 *
	 * @param userId the user ID of this postal
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this postal.
	 *
	 * @return the user uuid of this postal
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this postal.
	 *
	 * @param userUuid the user uuid of this postal
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this postal.
	 *
	 * @return the user name of this postal
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this postal.
	 *
	 * @param userName the user name of this postal
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this postal.
	 *
	 * @return the create date of this postal
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this postal.
	 *
	 * @param createDate the create date of this postal
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this postal.
	 *
	 * @return the modified date of this postal
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this postal.
	 *
	 * @param modifiedDate the modified date of this postal
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the postal mode of this postal.
	 *
	 * @return the postal mode of this postal
	 */
	@AutoEscape
	public String getPostalMode();

	/**
	 * Sets the postal mode of this postal.
	 *
	 * @param postalMode the postal mode of this postal
	 */
	public void setPostalMode(String postalMode);

	/**
	 * Returns the postal charge of this postal.
	 *
	 * @return the postal charge of this postal
	 */
	@AutoEscape
	public String getPostalCharge();

	/**
	 * Sets the postal charge of this postal.
	 *
	 * @param postalCharge the postal charge of this postal
	 */
	public void setPostalCharge(String postalCharge);

	/**
	 * Returns the medium of this postal.
	 *
	 * @return the medium of this postal
	 */
	@AutoEscape
	public String getMedium();

	/**
	 * Sets the medium of this postal.
	 *
	 * @param medium the medium of this postal
	 */
	public void setMedium(String medium);

	/**
	 * Returns the weight of this postal.
	 *
	 * @return the weight of this postal
	 */
	@AutoEscape
	public String getWeight();

	/**
	 * Sets the weight of this postal.
	 *
	 * @param weight the weight of this postal
	 */
	public void setWeight(String weight);

	/**
	 * Returns the mode no of this postal.
	 *
	 * @return the mode no of this postal
	 */
	public long getModeNo();

	/**
	 * Sets the mode no of this postal.
	 *
	 * @param modeNo the mode no of this postal
	 */
	public void setModeNo(long modeNo);

	/**
	 * Returns the peon book no of this postal.
	 *
	 * @return the peon book no of this postal
	 */
	@AutoEscape
	public String getPeonBookNo();

	/**
	 * Sets the peon book no of this postal.
	 *
	 * @param peonBookNo the peon book no of this postal
	 */
	public void setPeonBookNo(String peonBookNo);

	/**
	 * Returns the peon name of this postal.
	 *
	 * @return the peon name of this postal
	 */
	@AutoEscape
	public String getPeonName();

	/**
	 * Sets the peon name of this postal.
	 *
	 * @param peonName the peon name of this postal
	 */
	public void setPeonName(String peonName);

	/**
	 * Returns the out date of this postal.
	 *
	 * @return the out date of this postal
	 */
	public Date getOutDate();

	/**
	 * Sets the out date of this postal.
	 *
	 * @param outDate the out date of this postal
	 */
	public void setOutDate(Date outDate);

	/**
	 * Returns the delivery date of this postal.
	 *
	 * @return the delivery date of this postal
	 */
	public Date getDeliveryDate();

	/**
	 * Sets the delivery date of this postal.
	 *
	 * @param deliveryDate the delivery date of this postal
	 */
	public void setDeliveryDate(Date deliveryDate);

	/**
	 * Returns the delivery status of this postal.
	 *
	 * @return the delivery status of this postal
	 */
	@AutoEscape
	public String getDeliveryStatus();

	/**
	 * Sets the delivery status of this postal.
	 *
	 * @param deliveryStatus the delivery status of this postal
	 */
	public void setDeliveryStatus(String deliveryStatus);

	@Override
	public Postal cloneWithOriginalValues();

}