/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package io.jetprocess.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SecondaryHead service. Represents a row in the &quot;JP_SecondaryHead&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>io.jetprocess.model.impl.SecondaryHeadModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>io.jetprocess.model.impl.SecondaryHeadImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SecondaryHead
 * @generated
 */
@ProviderType
public interface SecondaryHeadModel extends BaseModel<SecondaryHead> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a secondary head model instance should use the {@link SecondaryHead} interface instead.
	 */

	/**
	 * Returns the primary key of this secondary head.
	 *
	 * @return the primary key of this secondary head
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this secondary head.
	 *
	 * @param primaryKey the primary key of this secondary head
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the secondary head ID of this secondary head.
	 *
	 * @return the secondary head ID of this secondary head
	 */
	public long getSecondaryHeadId();

	/**
	 * Sets the secondary head ID of this secondary head.
	 *
	 * @param secondaryHeadId the secondary head ID of this secondary head
	 */
	public void setSecondaryHeadId(long secondaryHeadId);

	/**
	 * Returns the secondary head value of this secondary head.
	 *
	 * @return the secondary head value of this secondary head
	 */
	@AutoEscape
	public String getSecondaryHeadValue();

	/**
	 * Sets the secondary head value of this secondary head.
	 *
	 * @param secondaryHeadValue the secondary head value of this secondary head
	 */
	public void setSecondaryHeadValue(String secondaryHeadValue);

	/**
	 * Returns the primary head ID of this secondary head.
	 *
	 * @return the primary head ID of this secondary head
	 */
	public long getPrimaryHeadId();

	/**
	 * Sets the primary head ID of this secondary head.
	 *
	 * @param primaryHeadId the primary head ID of this secondary head
	 */
	public void setPrimaryHeadId(long primaryHeadId);

	@Override
	public SecondaryHead cloneWithOriginalValues();

}