info:
    description: "JetProcessRs REST API"
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "JetProcessRs"
    version: v1.0
openapi: 3.0.1
components:
  schemas:
    FileRsModel:
      description: Contains all the data for file creation.
      properties:
        docFileId:
          format: int64
          type: integer
        groupId:
          format: int64
          type: integer
        nature:
          type: string
        type:
          type: string 
        headId:
          format: int64
          type: integer
        fileCodeId:
          format: int64
          type: integer
        subject:
          type: string
        fileNo:
          type: string
        categoryId:
          format: int64
          type: integer 
        remarks:
          type: string 
        reference:
          type: string 
        year:
          format: int64
          type: integer
        userPostId:
          format: int64
          type: integer   
        currentUser:
          format: int64
          type: integer
        currentState:
          format: int32
          type: integer
        dealingOrganizationId:
          format: int64
          type: integer
      type: object 
      
    BasicHeadRsModel:
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
        basicHeadCode:
          type: string       
      type: object
      
    PrimaryHeadRsModel:
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
        basicHeadId:
          format: int64
          type: integer     
      type: object
    
    SecondaryHeadRsModel:
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
        primaryHeadId:
          format: int64
          type: integer     
      type: object
      
    TertiaryHeadRsModel:
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
        secondaryHeadId:
          format: int64
          type: integer     
      type: object
      
    CategoryRsModel:
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
      type: object  
    
      
      
paths:
  /DocFile:
    post:
      operationId: createDocFile
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FileRsModel"
          application/xml:
            schema:
              $ref: "#/components/schemas/FileRsModel"
      responses:
        '200':
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/FileRsModel'
            application/xml:
              schema:
                  $ref: '#/components/schemas/FileRsModel'
          description: ''
      tags: ["FileRsModel"]
    get:
      operationId: getDocFileById
      parameters:
        - in: "query"
          name: docFileId
          required: true
          schema:
            format: int64
            type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/FileRsModel'
            application/xml:
              schema:
                  $ref: '#/components/schemas/FileRsModel'
          description: ''
      tags: ["FileRsModel"]
    delete:
      operationId: deleteDocFileById
      parameters:
        - in: "query"
          name: docFileId
          required: true
          schema:
            format: int64
            type: integer
      responses:
        '200':
          content:
            application/json: {}
            application/xml: {}
          description: ''
      tags: ["FileRsModel"]
    put:
      operationId: updateDocFile
      parameters:
        - in: "query"
          name: docFileId
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FileRsModel"
          application/xml:
            schema:
              $ref: "#/components/schemas/FileRsModel"
      responses:
        '200':
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/FileRsModel'
            application/xml:
              schema:
                  $ref: '#/components/schemas/FileRsModel'
          description: ''
      tags: ["FileRsModel"]
  /DocFiles:
    get:
      operationId: getDocFileList
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/FileRsModel'
            application/xml:
              schema:
                items:
                  $ref: '#/components/schemas/FileRsModel'
          description: ''
      tags: ["FileRsModel"]
  /primaryHead/{basicHeadId}:
    get:
      operationId: getPrimaryHeadByBasicHeadId
      parameters:
        - in: query
          name: basicHeadId
          required: true
          schema:
            format: int64
            type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/PrimaryHeadRsModel'
                type: array  
            application/xml:
              schema:
                items:
                  $ref: '#/components/schemas/PrimaryHeadRsModel'
                type: array
          description: ''
      tags: ["PrimaryHeadRsModel"]
      
  /SecondaryHead/{primaryHeadId}:
    get:
      operationId: getSeondaryHeadByPrimaryHeadId
      parameters:
        - in: query
          name: primaryHeadId
          required: true
          schema:
            format: int64
            type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/SecondaryHeadRsModel'
                type: array  
            application/xml:
              schema:
                items:
                  $ref: '#/components/schemas/SecondaryHeadRsModel'
                type: array
          description: ''
      tags: ["SecondaryHeadRsModel"]    
      
  /TertiaryHead/{secondaryHeadId}:
    get:
      operationId: getTertiaryHeadBySecondaryHeadId
      parameters:
        - in: query
          name: secondaryHeadId
          required: true
          schema:
            format: int64
            type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/TertiaryHeadRsModel'
                type: array  
            application/xml:
              schema:
                items:
                  $ref: '#/components/schemas/TertiaryHeadRsModel'
                type: array
          description: ''
      tags: ["TertiaryHeadRsModel"] 
  /BasicHead:
    get:
      operationId: getBasicHeadList
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/BasicHeadRsModel'
            application/xml:
              schema:
                items:
                  $ref: '#/components/schemas/BasicHeadRsModel'
          description: ''
      tags: ["BasicHeadRsModel"]  
  /Category:
    get:
      operationId: getCategoryList
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/CategoryRsModel'
            application/xml:
              schema:
                items:
                  $ref: '#/components/schemas/CategoryRsModel'
          description: ''
      tags: ["CategoryRsModel"]     
      