/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package io.jetprocess.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import io.jetprocess.model.BasicHead;
import io.jetprocess.model.BasicHeadModel;
import io.jetprocess.model.BasicHeadSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the BasicHead service. Represents a row in the &quot;JP_BasicHead&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>BasicHeadModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BasicHeadImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BasicHeadImpl
 * @generated
 */
@JSON(strict = true)
public class BasicHeadModelImpl
	extends BaseModelImpl<BasicHead> implements BasicHeadModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a basic head model instance should use the <code>BasicHead</code> interface instead.
	 */
	public static final String TABLE_NAME = "JP_BasicHead";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"basicHeadId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"basicHeadValue", Types.VARCHAR}, {"basicHeadCode", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("basicHeadId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("basicHeadValue", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("basicHeadCode", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table JP_BasicHead (uuid_ VARCHAR(75) null,basicHeadId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,basicHeadValue VARCHAR(75) null,basicHeadCode LONG)";

	public static final String TABLE_SQL_DROP = "drop table JP_BasicHead";

	public static final String ORDER_BY_JPQL =
		" ORDER BY basicHead.basicHeadId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY JP_BasicHead.basicHeadId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long BASICHEADID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static BasicHead toModel(BasicHeadSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		BasicHead model = new BasicHeadImpl();

		model.setUuid(soapModel.getUuid());
		model.setBasicHeadId(soapModel.getBasicHeadId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setBasicHeadValue(soapModel.getBasicHeadValue());
		model.setBasicHeadCode(soapModel.getBasicHeadCode());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<BasicHead> toModels(BasicHeadSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<BasicHead> models = new ArrayList<BasicHead>(soapModels.length);

		for (BasicHeadSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public BasicHeadModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _basicHeadId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBasicHeadId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _basicHeadId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return BasicHead.class;
	}

	@Override
	public String getModelClassName() {
		return BasicHead.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<BasicHead, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<BasicHead, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BasicHead, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((BasicHead)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<BasicHead, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<BasicHead, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(BasicHead)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<BasicHead, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<BasicHead, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, BasicHead>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			BasicHead.class.getClassLoader(), BasicHead.class,
			ModelWrapper.class);

		try {
			Constructor<BasicHead> constructor =
				(Constructor<BasicHead>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<BasicHead, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<BasicHead, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<BasicHead, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<BasicHead, Object>>();
		Map<String, BiConsumer<BasicHead, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<BasicHead, ?>>();

		attributeGetterFunctions.put("uuid", BasicHead::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<BasicHead, String>)BasicHead::setUuid);
		attributeGetterFunctions.put("basicHeadId", BasicHead::getBasicHeadId);
		attributeSetterBiConsumers.put(
			"basicHeadId",
			(BiConsumer<BasicHead, Long>)BasicHead::setBasicHeadId);
		attributeGetterFunctions.put("groupId", BasicHead::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<BasicHead, Long>)BasicHead::setGroupId);
		attributeGetterFunctions.put("companyId", BasicHead::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<BasicHead, Long>)BasicHead::setCompanyId);
		attributeGetterFunctions.put("userId", BasicHead::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<BasicHead, Long>)BasicHead::setUserId);
		attributeGetterFunctions.put("userName", BasicHead::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<BasicHead, String>)BasicHead::setUserName);
		attributeGetterFunctions.put("createDate", BasicHead::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<BasicHead, Date>)BasicHead::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", BasicHead::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<BasicHead, Date>)BasicHead::setModifiedDate);
		attributeGetterFunctions.put(
			"basicHeadValue", BasicHead::getBasicHeadValue);
		attributeSetterBiConsumers.put(
			"basicHeadValue",
			(BiConsumer<BasicHead, String>)BasicHead::setBasicHeadValue);
		attributeGetterFunctions.put(
			"basicHeadCode", BasicHead::getBasicHeadCode);
		attributeSetterBiConsumers.put(
			"basicHeadCode",
			(BiConsumer<BasicHead, Long>)BasicHead::setBasicHeadCode);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getBasicHeadId() {
		return _basicHeadId;
	}

	@Override
	public void setBasicHeadId(long basicHeadId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_basicHeadId = basicHeadId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getBasicHeadValue() {
		if (_basicHeadValue == null) {
			return "";
		}
		else {
			return _basicHeadValue;
		}
	}

	@Override
	public void setBasicHeadValue(String basicHeadValue) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_basicHeadValue = basicHeadValue;
	}

	@JSON
	@Override
	public long getBasicHeadCode() {
		return _basicHeadCode;
	}

	@Override
	public void setBasicHeadCode(long basicHeadCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_basicHeadCode = basicHeadCode;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(BasicHead.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), BasicHead.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public BasicHead toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, BasicHead>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BasicHeadImpl basicHeadImpl = new BasicHeadImpl();

		basicHeadImpl.setUuid(getUuid());
		basicHeadImpl.setBasicHeadId(getBasicHeadId());
		basicHeadImpl.setGroupId(getGroupId());
		basicHeadImpl.setCompanyId(getCompanyId());
		basicHeadImpl.setUserId(getUserId());
		basicHeadImpl.setUserName(getUserName());
		basicHeadImpl.setCreateDate(getCreateDate());
		basicHeadImpl.setModifiedDate(getModifiedDate());
		basicHeadImpl.setBasicHeadValue(getBasicHeadValue());
		basicHeadImpl.setBasicHeadCode(getBasicHeadCode());

		basicHeadImpl.resetOriginalValues();

		return basicHeadImpl;
	}

	@Override
	public BasicHead cloneWithOriginalValues() {
		BasicHeadImpl basicHeadImpl = new BasicHeadImpl();

		basicHeadImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		basicHeadImpl.setBasicHeadId(
			this.<Long>getColumnOriginalValue("basicHeadId"));
		basicHeadImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		basicHeadImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		basicHeadImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		basicHeadImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		basicHeadImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		basicHeadImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		basicHeadImpl.setBasicHeadValue(
			this.<String>getColumnOriginalValue("basicHeadValue"));
		basicHeadImpl.setBasicHeadCode(
			this.<Long>getColumnOriginalValue("basicHeadCode"));

		return basicHeadImpl;
	}

	@Override
	public int compareTo(BasicHead basicHead) {
		int value = 0;

		if (getBasicHeadId() < basicHead.getBasicHeadId()) {
			value = -1;
		}
		else if (getBasicHeadId() > basicHead.getBasicHeadId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof BasicHead)) {
			return false;
		}

		BasicHead basicHead = (BasicHead)object;

		long primaryKey = basicHead.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<BasicHead> toCacheModel() {
		BasicHeadCacheModel basicHeadCacheModel = new BasicHeadCacheModel();

		basicHeadCacheModel.uuid = getUuid();

		String uuid = basicHeadCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			basicHeadCacheModel.uuid = null;
		}

		basicHeadCacheModel.basicHeadId = getBasicHeadId();

		basicHeadCacheModel.groupId = getGroupId();

		basicHeadCacheModel.companyId = getCompanyId();

		basicHeadCacheModel.userId = getUserId();

		basicHeadCacheModel.userName = getUserName();

		String userName = basicHeadCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			basicHeadCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			basicHeadCacheModel.createDate = createDate.getTime();
		}
		else {
			basicHeadCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			basicHeadCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			basicHeadCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		basicHeadCacheModel.basicHeadValue = getBasicHeadValue();

		String basicHeadValue = basicHeadCacheModel.basicHeadValue;

		if ((basicHeadValue != null) && (basicHeadValue.length() == 0)) {
			basicHeadCacheModel.basicHeadValue = null;
		}

		basicHeadCacheModel.basicHeadCode = getBasicHeadCode();

		return basicHeadCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<BasicHead, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<BasicHead, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BasicHead, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((BasicHead)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<BasicHead, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<BasicHead, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BasicHead, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((BasicHead)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, BasicHead>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _basicHeadId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _basicHeadValue;
	private long _basicHeadCode;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<BasicHead, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((BasicHead)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("basicHeadId", _basicHeadId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("basicHeadValue", _basicHeadValue);
		_columnOriginalValues.put("basicHeadCode", _basicHeadCode);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("basicHeadId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("basicHeadValue", 256L);

		columnBitmasks.put("basicHeadCode", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private BasicHead _escapedModel;

}