/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package io.jetprocess.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import io.jetprocess.model.Dispatch;
import io.jetprocess.model.DispatchModel;
import io.jetprocess.model.DispatchSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Dispatch service. Represents a row in the &quot;JP_Dispatch&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DispatchModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DispatchImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DispatchImpl
 * @generated
 */
@JSON(strict = true)
public class DispatchModelImpl
	extends BaseModelImpl<Dispatch> implements DispatchModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dispatch model instance should use the <code>Dispatch</code> interface instead.
	 */
	public static final String TABLE_NAME = "JP_Dispatch";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"id_", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"dispatchNo", Types.VARCHAR}, {"dispatchBy", Types.VARCHAR},
		{"deliveryMode", Types.VARCHAR}, {"address", Types.VARCHAR},
		{"subject", Types.VARCHAR}, {"dispathOn", Types.VARCHAR},
		{"dispatchType", Types.VARCHAR}, {"issueNo", Types.VARCHAR},
		{"receiptentId", Types.BIGINT}, {"draftId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("dispatchNo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dispatchBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("deliveryMode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("address", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("subject", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dispathOn", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dispatchType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("issueNo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("receiptentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("draftId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table JP_Dispatch (uuid_ VARCHAR(75) null,id_ LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,dispatchNo VARCHAR(75) null,dispatchBy VARCHAR(75) null,deliveryMode VARCHAR(75) null,address VARCHAR(75) null,subject VARCHAR(75) null,dispathOn VARCHAR(75) null,dispatchType VARCHAR(75) null,issueNo VARCHAR(75) null,receiptentId LONG,draftId LONG)";

	public static final String TABLE_SQL_DROP = "drop table JP_Dispatch";

	public static final String ORDER_BY_JPQL = " ORDER BY dispatch.id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY JP_Dispatch.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static Dispatch toModel(DispatchSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Dispatch model = new DispatchImpl();

		model.setUuid(soapModel.getUuid());
		model.setId(soapModel.getId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setDispatchNo(soapModel.getDispatchNo());
		model.setDispatchBy(soapModel.getDispatchBy());
		model.setDeliveryMode(soapModel.getDeliveryMode());
		model.setAddress(soapModel.getAddress());
		model.setSubject(soapModel.getSubject());
		model.setDispathOn(soapModel.getDispathOn());
		model.setDispatchType(soapModel.getDispatchType());
		model.setIssueNo(soapModel.getIssueNo());
		model.setReceiptentId(soapModel.getReceiptentId());
		model.setDraftId(soapModel.getDraftId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<Dispatch> toModels(DispatchSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Dispatch> models = new ArrayList<Dispatch>(soapModels.length);

		for (DispatchSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public DispatchModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Dispatch.class;
	}

	@Override
	public String getModelClassName() {
		return Dispatch.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Dispatch, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Dispatch, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Dispatch, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Dispatch)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Dispatch, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Dispatch, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Dispatch)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Dispatch, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Dispatch, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Dispatch>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Dispatch.class.getClassLoader(), Dispatch.class,
			ModelWrapper.class);

		try {
			Constructor<Dispatch> constructor =
				(Constructor<Dispatch>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Dispatch, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Dispatch, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Dispatch, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Dispatch, Object>>();
		Map<String, BiConsumer<Dispatch, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Dispatch, ?>>();

		attributeGetterFunctions.put("uuid", Dispatch::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Dispatch, String>)Dispatch::setUuid);
		attributeGetterFunctions.put("id", Dispatch::getId);
		attributeSetterBiConsumers.put(
			"id", (BiConsumer<Dispatch, Long>)Dispatch::setId);
		attributeGetterFunctions.put("groupId", Dispatch::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Dispatch, Long>)Dispatch::setGroupId);
		attributeGetterFunctions.put("companyId", Dispatch::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Dispatch, Long>)Dispatch::setCompanyId);
		attributeGetterFunctions.put("userId", Dispatch::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Dispatch, Long>)Dispatch::setUserId);
		attributeGetterFunctions.put("userName", Dispatch::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Dispatch, String>)Dispatch::setUserName);
		attributeGetterFunctions.put("createDate", Dispatch::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Dispatch, Date>)Dispatch::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Dispatch::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<Dispatch, Date>)Dispatch::setModifiedDate);
		attributeGetterFunctions.put("dispatchNo", Dispatch::getDispatchNo);
		attributeSetterBiConsumers.put(
			"dispatchNo",
			(BiConsumer<Dispatch, String>)Dispatch::setDispatchNo);
		attributeGetterFunctions.put("dispatchBy", Dispatch::getDispatchBy);
		attributeSetterBiConsumers.put(
			"dispatchBy",
			(BiConsumer<Dispatch, String>)Dispatch::setDispatchBy);
		attributeGetterFunctions.put("deliveryMode", Dispatch::getDeliveryMode);
		attributeSetterBiConsumers.put(
			"deliveryMode",
			(BiConsumer<Dispatch, String>)Dispatch::setDeliveryMode);
		attributeGetterFunctions.put("address", Dispatch::getAddress);
		attributeSetterBiConsumers.put(
			"address", (BiConsumer<Dispatch, String>)Dispatch::setAddress);
		attributeGetterFunctions.put("subject", Dispatch::getSubject);
		attributeSetterBiConsumers.put(
			"subject", (BiConsumer<Dispatch, String>)Dispatch::setSubject);
		attributeGetterFunctions.put("dispathOn", Dispatch::getDispathOn);
		attributeSetterBiConsumers.put(
			"dispathOn", (BiConsumer<Dispatch, String>)Dispatch::setDispathOn);
		attributeGetterFunctions.put("dispatchType", Dispatch::getDispatchType);
		attributeSetterBiConsumers.put(
			"dispatchType",
			(BiConsumer<Dispatch, String>)Dispatch::setDispatchType);
		attributeGetterFunctions.put("issueNo", Dispatch::getIssueNo);
		attributeSetterBiConsumers.put(
			"issueNo", (BiConsumer<Dispatch, String>)Dispatch::setIssueNo);
		attributeGetterFunctions.put("receiptentId", Dispatch::getReceiptentId);
		attributeSetterBiConsumers.put(
			"receiptentId",
			(BiConsumer<Dispatch, Long>)Dispatch::setReceiptentId);
		attributeGetterFunctions.put("draftId", Dispatch::getDraftId);
		attributeSetterBiConsumers.put(
			"draftId", (BiConsumer<Dispatch, Long>)Dispatch::setDraftId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getDispatchNo() {
		if (_dispatchNo == null) {
			return "";
		}
		else {
			return _dispatchNo;
		}
	}

	@Override
	public void setDispatchNo(String dispatchNo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dispatchNo = dispatchNo;
	}

	@JSON
	@Override
	public String getDispatchBy() {
		if (_dispatchBy == null) {
			return "";
		}
		else {
			return _dispatchBy;
		}
	}

	@Override
	public void setDispatchBy(String dispatchBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dispatchBy = dispatchBy;
	}

	@JSON
	@Override
	public String getDeliveryMode() {
		if (_deliveryMode == null) {
			return "";
		}
		else {
			return _deliveryMode;
		}
	}

	@Override
	public void setDeliveryMode(String deliveryMode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_deliveryMode = deliveryMode;
	}

	@JSON
	@Override
	public String getAddress() {
		if (_address == null) {
			return "";
		}
		else {
			return _address;
		}
	}

	@Override
	public void setAddress(String address) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_address = address;
	}

	@JSON
	@Override
	public String getSubject() {
		if (_subject == null) {
			return "";
		}
		else {
			return _subject;
		}
	}

	@Override
	public void setSubject(String subject) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_subject = subject;
	}

	@JSON
	@Override
	public String getDispathOn() {
		if (_dispathOn == null) {
			return "";
		}
		else {
			return _dispathOn;
		}
	}

	@Override
	public void setDispathOn(String dispathOn) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dispathOn = dispathOn;
	}

	@JSON
	@Override
	public String getDispatchType() {
		if (_dispatchType == null) {
			return "";
		}
		else {
			return _dispatchType;
		}
	}

	@Override
	public void setDispatchType(String dispatchType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dispatchType = dispatchType;
	}

	@JSON
	@Override
	public String getIssueNo() {
		if (_issueNo == null) {
			return "";
		}
		else {
			return _issueNo;
		}
	}

	@Override
	public void setIssueNo(String issueNo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_issueNo = issueNo;
	}

	@JSON
	@Override
	public long getReceiptentId() {
		return _receiptentId;
	}

	@Override
	public void setReceiptentId(long receiptentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_receiptentId = receiptentId;
	}

	@JSON
	@Override
	public long getDraftId() {
		return _draftId;
	}

	@Override
	public void setDraftId(long draftId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_draftId = draftId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Dispatch.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Dispatch.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Dispatch toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Dispatch>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DispatchImpl dispatchImpl = new DispatchImpl();

		dispatchImpl.setUuid(getUuid());
		dispatchImpl.setId(getId());
		dispatchImpl.setGroupId(getGroupId());
		dispatchImpl.setCompanyId(getCompanyId());
		dispatchImpl.setUserId(getUserId());
		dispatchImpl.setUserName(getUserName());
		dispatchImpl.setCreateDate(getCreateDate());
		dispatchImpl.setModifiedDate(getModifiedDate());
		dispatchImpl.setDispatchNo(getDispatchNo());
		dispatchImpl.setDispatchBy(getDispatchBy());
		dispatchImpl.setDeliveryMode(getDeliveryMode());
		dispatchImpl.setAddress(getAddress());
		dispatchImpl.setSubject(getSubject());
		dispatchImpl.setDispathOn(getDispathOn());
		dispatchImpl.setDispatchType(getDispatchType());
		dispatchImpl.setIssueNo(getIssueNo());
		dispatchImpl.setReceiptentId(getReceiptentId());
		dispatchImpl.setDraftId(getDraftId());

		dispatchImpl.resetOriginalValues();

		return dispatchImpl;
	}

	@Override
	public Dispatch cloneWithOriginalValues() {
		DispatchImpl dispatchImpl = new DispatchImpl();

		dispatchImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		dispatchImpl.setId(this.<Long>getColumnOriginalValue("id_"));
		dispatchImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		dispatchImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		dispatchImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		dispatchImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		dispatchImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		dispatchImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		dispatchImpl.setDispatchNo(
			this.<String>getColumnOriginalValue("dispatchNo"));
		dispatchImpl.setDispatchBy(
			this.<String>getColumnOriginalValue("dispatchBy"));
		dispatchImpl.setDeliveryMode(
			this.<String>getColumnOriginalValue("deliveryMode"));
		dispatchImpl.setAddress(this.<String>getColumnOriginalValue("address"));
		dispatchImpl.setSubject(this.<String>getColumnOriginalValue("subject"));
		dispatchImpl.setDispathOn(
			this.<String>getColumnOriginalValue("dispathOn"));
		dispatchImpl.setDispatchType(
			this.<String>getColumnOriginalValue("dispatchType"));
		dispatchImpl.setIssueNo(this.<String>getColumnOriginalValue("issueNo"));
		dispatchImpl.setReceiptentId(
			this.<Long>getColumnOriginalValue("receiptentId"));
		dispatchImpl.setDraftId(this.<Long>getColumnOriginalValue("draftId"));

		return dispatchImpl;
	}

	@Override
	public int compareTo(Dispatch dispatch) {
		long primaryKey = dispatch.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Dispatch)) {
			return false;
		}

		Dispatch dispatch = (Dispatch)object;

		long primaryKey = dispatch.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Dispatch> toCacheModel() {
		DispatchCacheModel dispatchCacheModel = new DispatchCacheModel();

		dispatchCacheModel.uuid = getUuid();

		String uuid = dispatchCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			dispatchCacheModel.uuid = null;
		}

		dispatchCacheModel.id = getId();

		dispatchCacheModel.groupId = getGroupId();

		dispatchCacheModel.companyId = getCompanyId();

		dispatchCacheModel.userId = getUserId();

		dispatchCacheModel.userName = getUserName();

		String userName = dispatchCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			dispatchCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			dispatchCacheModel.createDate = createDate.getTime();
		}
		else {
			dispatchCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			dispatchCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			dispatchCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		dispatchCacheModel.dispatchNo = getDispatchNo();

		String dispatchNo = dispatchCacheModel.dispatchNo;

		if ((dispatchNo != null) && (dispatchNo.length() == 0)) {
			dispatchCacheModel.dispatchNo = null;
		}

		dispatchCacheModel.dispatchBy = getDispatchBy();

		String dispatchBy = dispatchCacheModel.dispatchBy;

		if ((dispatchBy != null) && (dispatchBy.length() == 0)) {
			dispatchCacheModel.dispatchBy = null;
		}

		dispatchCacheModel.deliveryMode = getDeliveryMode();

		String deliveryMode = dispatchCacheModel.deliveryMode;

		if ((deliveryMode != null) && (deliveryMode.length() == 0)) {
			dispatchCacheModel.deliveryMode = null;
		}

		dispatchCacheModel.address = getAddress();

		String address = dispatchCacheModel.address;

		if ((address != null) && (address.length() == 0)) {
			dispatchCacheModel.address = null;
		}

		dispatchCacheModel.subject = getSubject();

		String subject = dispatchCacheModel.subject;

		if ((subject != null) && (subject.length() == 0)) {
			dispatchCacheModel.subject = null;
		}

		dispatchCacheModel.dispathOn = getDispathOn();

		String dispathOn = dispatchCacheModel.dispathOn;

		if ((dispathOn != null) && (dispathOn.length() == 0)) {
			dispatchCacheModel.dispathOn = null;
		}

		dispatchCacheModel.dispatchType = getDispatchType();

		String dispatchType = dispatchCacheModel.dispatchType;

		if ((dispatchType != null) && (dispatchType.length() == 0)) {
			dispatchCacheModel.dispatchType = null;
		}

		dispatchCacheModel.issueNo = getIssueNo();

		String issueNo = dispatchCacheModel.issueNo;

		if ((issueNo != null) && (issueNo.length() == 0)) {
			dispatchCacheModel.issueNo = null;
		}

		dispatchCacheModel.receiptentId = getReceiptentId();

		dispatchCacheModel.draftId = getDraftId();

		return dispatchCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Dispatch, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Dispatch, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Dispatch, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Dispatch)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Dispatch, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Dispatch, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Dispatch, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Dispatch)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Dispatch>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _id;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _dispatchNo;
	private String _dispatchBy;
	private String _deliveryMode;
	private String _address;
	private String _subject;
	private String _dispathOn;
	private String _dispatchType;
	private String _issueNo;
	private long _receiptentId;
	private long _draftId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Dispatch, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Dispatch)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("dispatchNo", _dispatchNo);
		_columnOriginalValues.put("dispatchBy", _dispatchBy);
		_columnOriginalValues.put("deliveryMode", _deliveryMode);
		_columnOriginalValues.put("address", _address);
		_columnOriginalValues.put("subject", _subject);
		_columnOriginalValues.put("dispathOn", _dispathOn);
		_columnOriginalValues.put("dispatchType", _dispatchType);
		_columnOriginalValues.put("issueNo", _issueNo);
		_columnOriginalValues.put("receiptentId", _receiptentId);
		_columnOriginalValues.put("draftId", _draftId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("id_", "id");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("id_", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("dispatchNo", 256L);

		columnBitmasks.put("dispatchBy", 512L);

		columnBitmasks.put("deliveryMode", 1024L);

		columnBitmasks.put("address", 2048L);

		columnBitmasks.put("subject", 4096L);

		columnBitmasks.put("dispathOn", 8192L);

		columnBitmasks.put("dispatchType", 16384L);

		columnBitmasks.put("issueNo", 32768L);

		columnBitmasks.put("receiptentId", 65536L);

		columnBitmasks.put("draftId", 131072L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Dispatch _escapedModel;

}