/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package io.jetprocess.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import io.jetprocess.model.Receipt;
import io.jetprocess.model.ReceiptModel;
import io.jetprocess.model.ReceiptSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Receipt service. Represents a row in the &quot;JP_Receipt&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ReceiptModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ReceiptImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ReceiptImpl
 * @generated
 */
@JSON(strict = true)
public class ReceiptModelImpl
	extends BaseModelImpl<Receipt> implements ReceiptModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a receipt model instance should use the <code>Receipt</code> interface instead.
	 */
	public static final String TABLE_NAME = "JP_Receipt";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"receiptId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"typeId", Types.BIGINT}, {"deliveryModeId", Types.BIGINT},
		{"receivedOn", Types.VARCHAR}, {"letterDate", Types.VARCHAR},
		{"referenceNo", Types.VARCHAR}, {"modeNo", Types.VARCHAR},
		{"CategoryId", Types.BIGINT}, {"subject", Types.VARCHAR},
		{"remarks", Types.VARCHAR}, {"name", Types.VARCHAR},
		{"designation", Types.VARCHAR}, {"mobile", Types.VARCHAR},
		{"email", Types.VARCHAR}, {"address", Types.VARCHAR},
		{"stateId", Types.BIGINT}, {"pinCode", Types.VARCHAR},
		{"receiptNo", Types.VARCHAR}, {"organizationId", Types.BIGINT},
		{"city", Types.VARCHAR}, {"userPostId", Types.BIGINT},
		{"viewPdfUrl", Types.VARCHAR}, {"docFileId", Types.BIGINT},
		{"nature", Types.VARCHAR}, {"currentlyWith", Types.BIGINT},
		{"currentState", Types.INTEGER}, {"attachStatus", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("receiptId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("typeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("deliveryModeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("receivedOn", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("letterDate", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("referenceNo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("modeNo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CategoryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("subject", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("remarks", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("designation", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("mobile", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("email", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("address", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("stateId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("pinCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("receiptNo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("organizationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("city", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("userPostId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("viewPdfUrl", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("docFileId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("nature", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("currentlyWith", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("currentState", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("attachStatus", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table JP_Receipt (uuid_ VARCHAR(75) null,receiptId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,typeId LONG,deliveryModeId LONG,receivedOn VARCHAR(75) null,letterDate VARCHAR(75) null,referenceNo VARCHAR(75) null,modeNo VARCHAR(75) null,CategoryId LONG,subject VARCHAR(75) null,remarks VARCHAR(75) null,name VARCHAR(75) null,designation VARCHAR(75) null,mobile VARCHAR(75) null,email VARCHAR(75) null,address VARCHAR(75) null,stateId LONG,pinCode VARCHAR(75) null,receiptNo VARCHAR(75) null,organizationId LONG,city VARCHAR(75) null,userPostId LONG,viewPdfUrl VARCHAR(75) null,docFileId LONG,nature VARCHAR(75) null,currentlyWith LONG,currentState INTEGER,attachStatus VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table JP_Receipt";

	public static final String ORDER_BY_JPQL =
		" ORDER BY receipt.receiptId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY JP_Receipt.receiptId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long RECEIPTID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static Receipt toModel(ReceiptSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Receipt model = new ReceiptImpl();

		model.setUuid(soapModel.getUuid());
		model.setReceiptId(soapModel.getReceiptId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setTypeId(soapModel.getTypeId());
		model.setDeliveryModeId(soapModel.getDeliveryModeId());
		model.setReceivedOn(soapModel.getReceivedOn());
		model.setLetterDate(soapModel.getLetterDate());
		model.setReferenceNo(soapModel.getReferenceNo());
		model.setModeNo(soapModel.getModeNo());
		model.setCategoryId(soapModel.getCategoryId());
		model.setSubject(soapModel.getSubject());
		model.setRemarks(soapModel.getRemarks());
		model.setName(soapModel.getName());
		model.setDesignation(soapModel.getDesignation());
		model.setMobile(soapModel.getMobile());
		model.setEmail(soapModel.getEmail());
		model.setAddress(soapModel.getAddress());
		model.setStateId(soapModel.getStateId());
		model.setPinCode(soapModel.getPinCode());
		model.setReceiptNo(soapModel.getReceiptNo());
		model.setOrganizationId(soapModel.getOrganizationId());
		model.setCity(soapModel.getCity());
		model.setUserPostId(soapModel.getUserPostId());
		model.setViewPdfUrl(soapModel.getViewPdfUrl());
		model.setDocFileId(soapModel.getDocFileId());
		model.setNature(soapModel.getNature());
		model.setCurrentlyWith(soapModel.getCurrentlyWith());
		model.setCurrentState(soapModel.getCurrentState());
		model.setAttachStatus(soapModel.getAttachStatus());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<Receipt> toModels(ReceiptSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Receipt> models = new ArrayList<Receipt>(soapModels.length);

		for (ReceiptSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public ReceiptModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _receiptId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setReceiptId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _receiptId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Receipt.class;
	}

	@Override
	public String getModelClassName() {
		return Receipt.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Receipt, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Receipt, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Receipt, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Receipt)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Receipt, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Receipt, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Receipt)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Receipt, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Receipt, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Receipt>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Receipt.class.getClassLoader(), Receipt.class, ModelWrapper.class);

		try {
			Constructor<Receipt> constructor =
				(Constructor<Receipt>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Receipt, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Receipt, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Receipt, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Receipt, Object>>();
		Map<String, BiConsumer<Receipt, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Receipt, ?>>();

		attributeGetterFunctions.put("uuid", Receipt::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Receipt, String>)Receipt::setUuid);
		attributeGetterFunctions.put("receiptId", Receipt::getReceiptId);
		attributeSetterBiConsumers.put(
			"receiptId", (BiConsumer<Receipt, Long>)Receipt::setReceiptId);
		attributeGetterFunctions.put("groupId", Receipt::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Receipt, Long>)Receipt::setGroupId);
		attributeGetterFunctions.put("companyId", Receipt::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Receipt, Long>)Receipt::setCompanyId);
		attributeGetterFunctions.put("userId", Receipt::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Receipt, Long>)Receipt::setUserId);
		attributeGetterFunctions.put("userName", Receipt::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Receipt, String>)Receipt::setUserName);
		attributeGetterFunctions.put("createDate", Receipt::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Receipt, Date>)Receipt::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Receipt::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<Receipt, Date>)Receipt::setModifiedDate);
		attributeGetterFunctions.put("typeId", Receipt::getTypeId);
		attributeSetterBiConsumers.put(
			"typeId", (BiConsumer<Receipt, Long>)Receipt::setTypeId);
		attributeGetterFunctions.put(
			"deliveryModeId", Receipt::getDeliveryModeId);
		attributeSetterBiConsumers.put(
			"deliveryModeId",
			(BiConsumer<Receipt, Long>)Receipt::setDeliveryModeId);
		attributeGetterFunctions.put("receivedOn", Receipt::getReceivedOn);
		attributeSetterBiConsumers.put(
			"receivedOn", (BiConsumer<Receipt, String>)Receipt::setReceivedOn);
		attributeGetterFunctions.put("letterDate", Receipt::getLetterDate);
		attributeSetterBiConsumers.put(
			"letterDate", (BiConsumer<Receipt, String>)Receipt::setLetterDate);
		attributeGetterFunctions.put("referenceNo", Receipt::getReferenceNo);
		attributeSetterBiConsumers.put(
			"referenceNo",
			(BiConsumer<Receipt, String>)Receipt::setReferenceNo);
		attributeGetterFunctions.put("modeNo", Receipt::getModeNo);
		attributeSetterBiConsumers.put(
			"modeNo", (BiConsumer<Receipt, String>)Receipt::setModeNo);
		attributeGetterFunctions.put("CategoryId", Receipt::getCategoryId);
		attributeSetterBiConsumers.put(
			"CategoryId", (BiConsumer<Receipt, Long>)Receipt::setCategoryId);
		attributeGetterFunctions.put("subject", Receipt::getSubject);
		attributeSetterBiConsumers.put(
			"subject", (BiConsumer<Receipt, String>)Receipt::setSubject);
		attributeGetterFunctions.put("remarks", Receipt::getRemarks);
		attributeSetterBiConsumers.put(
			"remarks", (BiConsumer<Receipt, String>)Receipt::setRemarks);
		attributeGetterFunctions.put("name", Receipt::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<Receipt, String>)Receipt::setName);
		attributeGetterFunctions.put("designation", Receipt::getDesignation);
		attributeSetterBiConsumers.put(
			"designation",
			(BiConsumer<Receipt, String>)Receipt::setDesignation);
		attributeGetterFunctions.put("mobile", Receipt::getMobile);
		attributeSetterBiConsumers.put(
			"mobile", (BiConsumer<Receipt, String>)Receipt::setMobile);
		attributeGetterFunctions.put("email", Receipt::getEmail);
		attributeSetterBiConsumers.put(
			"email", (BiConsumer<Receipt, String>)Receipt::setEmail);
		attributeGetterFunctions.put("address", Receipt::getAddress);
		attributeSetterBiConsumers.put(
			"address", (BiConsumer<Receipt, String>)Receipt::setAddress);
		attributeGetterFunctions.put("stateId", Receipt::getStateId);
		attributeSetterBiConsumers.put(
			"stateId", (BiConsumer<Receipt, Long>)Receipt::setStateId);
		attributeGetterFunctions.put("pinCode", Receipt::getPinCode);
		attributeSetterBiConsumers.put(
			"pinCode", (BiConsumer<Receipt, String>)Receipt::setPinCode);
		attributeGetterFunctions.put("receiptNo", Receipt::getReceiptNo);
		attributeSetterBiConsumers.put(
			"receiptNo", (BiConsumer<Receipt, String>)Receipt::setReceiptNo);
		attributeGetterFunctions.put(
			"organizationId", Receipt::getOrganizationId);
		attributeSetterBiConsumers.put(
			"organizationId",
			(BiConsumer<Receipt, Long>)Receipt::setOrganizationId);
		attributeGetterFunctions.put("city", Receipt::getCity);
		attributeSetterBiConsumers.put(
			"city", (BiConsumer<Receipt, String>)Receipt::setCity);
		attributeGetterFunctions.put("userPostId", Receipt::getUserPostId);
		attributeSetterBiConsumers.put(
			"userPostId", (BiConsumer<Receipt, Long>)Receipt::setUserPostId);
		attributeGetterFunctions.put("viewPdfUrl", Receipt::getViewPdfUrl);
		attributeSetterBiConsumers.put(
			"viewPdfUrl", (BiConsumer<Receipt, String>)Receipt::setViewPdfUrl);
		attributeGetterFunctions.put("docFileId", Receipt::getDocFileId);
		attributeSetterBiConsumers.put(
			"docFileId", (BiConsumer<Receipt, Long>)Receipt::setDocFileId);
		attributeGetterFunctions.put("nature", Receipt::getNature);
		attributeSetterBiConsumers.put(
			"nature", (BiConsumer<Receipt, String>)Receipt::setNature);
		attributeGetterFunctions.put(
			"currentlyWith", Receipt::getCurrentlyWith);
		attributeSetterBiConsumers.put(
			"currentlyWith",
			(BiConsumer<Receipt, Long>)Receipt::setCurrentlyWith);
		attributeGetterFunctions.put("currentState", Receipt::getCurrentState);
		attributeSetterBiConsumers.put(
			"currentState",
			(BiConsumer<Receipt, Integer>)Receipt::setCurrentState);
		attributeGetterFunctions.put("attachStatus", Receipt::getAttachStatus);
		attributeSetterBiConsumers.put(
			"attachStatus",
			(BiConsumer<Receipt, String>)Receipt::setAttachStatus);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getReceiptId() {
		return _receiptId;
	}

	@Override
	public void setReceiptId(long receiptId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_receiptId = receiptId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getTypeId() {
		return _typeId;
	}

	@Override
	public void setTypeId(long typeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_typeId = typeId;
	}

	@JSON
	@Override
	public long getDeliveryModeId() {
		return _deliveryModeId;
	}

	@Override
	public void setDeliveryModeId(long deliveryModeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_deliveryModeId = deliveryModeId;
	}

	@JSON
	@Override
	public String getReceivedOn() {
		if (_receivedOn == null) {
			return "";
		}
		else {
			return _receivedOn;
		}
	}

	@Override
	public void setReceivedOn(String receivedOn) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_receivedOn = receivedOn;
	}

	@JSON
	@Override
	public String getLetterDate() {
		if (_letterDate == null) {
			return "";
		}
		else {
			return _letterDate;
		}
	}

	@Override
	public void setLetterDate(String letterDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_letterDate = letterDate;
	}

	@JSON
	@Override
	public String getReferenceNo() {
		if (_referenceNo == null) {
			return "";
		}
		else {
			return _referenceNo;
		}
	}

	@Override
	public void setReferenceNo(String referenceNo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_referenceNo = referenceNo;
	}

	@JSON
	@Override
	public String getModeNo() {
		if (_modeNo == null) {
			return "";
		}
		else {
			return _modeNo;
		}
	}

	@Override
	public void setModeNo(String modeNo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modeNo = modeNo;
	}

	@JSON
	@Override
	public long getCategoryId() {
		return _CategoryId;
	}

	@Override
	public void setCategoryId(long CategoryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CategoryId = CategoryId;
	}

	@JSON
	@Override
	public String getSubject() {
		if (_subject == null) {
			return "";
		}
		else {
			return _subject;
		}
	}

	@Override
	public void setSubject(String subject) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_subject = subject;
	}

	@JSON
	@Override
	public String getRemarks() {
		if (_remarks == null) {
			return "";
		}
		else {
			return _remarks;
		}
	}

	@Override
	public void setRemarks(String remarks) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_remarks = remarks;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@JSON
	@Override
	public String getDesignation() {
		if (_designation == null) {
			return "";
		}
		else {
			return _designation;
		}
	}

	@Override
	public void setDesignation(String designation) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_designation = designation;
	}

	@JSON
	@Override
	public String getMobile() {
		if (_mobile == null) {
			return "";
		}
		else {
			return _mobile;
		}
	}

	@Override
	public void setMobile(String mobile) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mobile = mobile;
	}

	@JSON
	@Override
	public String getEmail() {
		if (_email == null) {
			return "";
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_email = email;
	}

	@JSON
	@Override
	public String getAddress() {
		if (_address == null) {
			return "";
		}
		else {
			return _address;
		}
	}

	@Override
	public void setAddress(String address) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_address = address;
	}

	@JSON
	@Override
	public long getStateId() {
		return _stateId;
	}

	@Override
	public void setStateId(long stateId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_stateId = stateId;
	}

	@JSON
	@Override
	public String getPinCode() {
		if (_pinCode == null) {
			return "";
		}
		else {
			return _pinCode;
		}
	}

	@Override
	public void setPinCode(String pinCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_pinCode = pinCode;
	}

	@JSON
	@Override
	public String getReceiptNo() {
		if (_receiptNo == null) {
			return "";
		}
		else {
			return _receiptNo;
		}
	}

	@Override
	public void setReceiptNo(String receiptNo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_receiptNo = receiptNo;
	}

	@JSON
	@Override
	public long getOrganizationId() {
		return _organizationId;
	}

	@Override
	public void setOrganizationId(long organizationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_organizationId = organizationId;
	}

	@JSON
	@Override
	public String getCity() {
		if (_city == null) {
			return "";
		}
		else {
			return _city;
		}
	}

	@Override
	public void setCity(String city) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_city = city;
	}

	@JSON
	@Override
	public long getUserPostId() {
		return _userPostId;
	}

	@Override
	public void setUserPostId(long userPostId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userPostId = userPostId;
	}

	@JSON
	@Override
	public String getViewPdfUrl() {
		if (_viewPdfUrl == null) {
			return "";
		}
		else {
			return _viewPdfUrl;
		}
	}

	@Override
	public void setViewPdfUrl(String viewPdfUrl) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_viewPdfUrl = viewPdfUrl;
	}

	@JSON
	@Override
	public long getDocFileId() {
		return _docFileId;
	}

	@Override
	public void setDocFileId(long docFileId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_docFileId = docFileId;
	}

	@JSON
	@Override
	public String getNature() {
		if (_nature == null) {
			return "";
		}
		else {
			return _nature;
		}
	}

	@Override
	public void setNature(String nature) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nature = nature;
	}

	@JSON
	@Override
	public long getCurrentlyWith() {
		return _currentlyWith;
	}

	@Override
	public void setCurrentlyWith(long currentlyWith) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_currentlyWith = currentlyWith;
	}

	@JSON
	@Override
	public int getCurrentState() {
		return _currentState;
	}

	@Override
	public void setCurrentState(int currentState) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_currentState = currentState;
	}

	@JSON
	@Override
	public String getAttachStatus() {
		if (_attachStatus == null) {
			return "";
		}
		else {
			return _attachStatus;
		}
	}

	@Override
	public void setAttachStatus(String attachStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_attachStatus = attachStatus;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Receipt.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Receipt.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Receipt toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Receipt>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ReceiptImpl receiptImpl = new ReceiptImpl();

		receiptImpl.setUuid(getUuid());
		receiptImpl.setReceiptId(getReceiptId());
		receiptImpl.setGroupId(getGroupId());
		receiptImpl.setCompanyId(getCompanyId());
		receiptImpl.setUserId(getUserId());
		receiptImpl.setUserName(getUserName());
		receiptImpl.setCreateDate(getCreateDate());
		receiptImpl.setModifiedDate(getModifiedDate());
		receiptImpl.setTypeId(getTypeId());
		receiptImpl.setDeliveryModeId(getDeliveryModeId());
		receiptImpl.setReceivedOn(getReceivedOn());
		receiptImpl.setLetterDate(getLetterDate());
		receiptImpl.setReferenceNo(getReferenceNo());
		receiptImpl.setModeNo(getModeNo());
		receiptImpl.setCategoryId(getCategoryId());
		receiptImpl.setSubject(getSubject());
		receiptImpl.setRemarks(getRemarks());
		receiptImpl.setName(getName());
		receiptImpl.setDesignation(getDesignation());
		receiptImpl.setMobile(getMobile());
		receiptImpl.setEmail(getEmail());
		receiptImpl.setAddress(getAddress());
		receiptImpl.setStateId(getStateId());
		receiptImpl.setPinCode(getPinCode());
		receiptImpl.setReceiptNo(getReceiptNo());
		receiptImpl.setOrganizationId(getOrganizationId());
		receiptImpl.setCity(getCity());
		receiptImpl.setUserPostId(getUserPostId());
		receiptImpl.setViewPdfUrl(getViewPdfUrl());
		receiptImpl.setDocFileId(getDocFileId());
		receiptImpl.setNature(getNature());
		receiptImpl.setCurrentlyWith(getCurrentlyWith());
		receiptImpl.setCurrentState(getCurrentState());
		receiptImpl.setAttachStatus(getAttachStatus());

		receiptImpl.resetOriginalValues();

		return receiptImpl;
	}

	@Override
	public Receipt cloneWithOriginalValues() {
		ReceiptImpl receiptImpl = new ReceiptImpl();

		receiptImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		receiptImpl.setReceiptId(
			this.<Long>getColumnOriginalValue("receiptId"));
		receiptImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		receiptImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		receiptImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		receiptImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		receiptImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		receiptImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		receiptImpl.setTypeId(this.<Long>getColumnOriginalValue("typeId"));
		receiptImpl.setDeliveryModeId(
			this.<Long>getColumnOriginalValue("deliveryModeId"));
		receiptImpl.setReceivedOn(
			this.<String>getColumnOriginalValue("receivedOn"));
		receiptImpl.setLetterDate(
			this.<String>getColumnOriginalValue("letterDate"));
		receiptImpl.setReferenceNo(
			this.<String>getColumnOriginalValue("referenceNo"));
		receiptImpl.setModeNo(this.<String>getColumnOriginalValue("modeNo"));
		receiptImpl.setCategoryId(
			this.<Long>getColumnOriginalValue("CategoryId"));
		receiptImpl.setSubject(this.<String>getColumnOriginalValue("subject"));
		receiptImpl.setRemarks(this.<String>getColumnOriginalValue("remarks"));
		receiptImpl.setName(this.<String>getColumnOriginalValue("name"));
		receiptImpl.setDesignation(
			this.<String>getColumnOriginalValue("designation"));
		receiptImpl.setMobile(this.<String>getColumnOriginalValue("mobile"));
		receiptImpl.setEmail(this.<String>getColumnOriginalValue("email"));
		receiptImpl.setAddress(this.<String>getColumnOriginalValue("address"));
		receiptImpl.setStateId(this.<Long>getColumnOriginalValue("stateId"));
		receiptImpl.setPinCode(this.<String>getColumnOriginalValue("pinCode"));
		receiptImpl.setReceiptNo(
			this.<String>getColumnOriginalValue("receiptNo"));
		receiptImpl.setOrganizationId(
			this.<Long>getColumnOriginalValue("organizationId"));
		receiptImpl.setCity(this.<String>getColumnOriginalValue("city"));
		receiptImpl.setUserPostId(
			this.<Long>getColumnOriginalValue("userPostId"));
		receiptImpl.setViewPdfUrl(
			this.<String>getColumnOriginalValue("viewPdfUrl"));
		receiptImpl.setDocFileId(
			this.<Long>getColumnOriginalValue("docFileId"));
		receiptImpl.setNature(this.<String>getColumnOriginalValue("nature"));
		receiptImpl.setCurrentlyWith(
			this.<Long>getColumnOriginalValue("currentlyWith"));
		receiptImpl.setCurrentState(
			this.<Integer>getColumnOriginalValue("currentState"));
		receiptImpl.setAttachStatus(
			this.<String>getColumnOriginalValue("attachStatus"));

		return receiptImpl;
	}

	@Override
	public int compareTo(Receipt receipt) {
		long primaryKey = receipt.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Receipt)) {
			return false;
		}

		Receipt receipt = (Receipt)object;

		long primaryKey = receipt.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Receipt> toCacheModel() {
		ReceiptCacheModel receiptCacheModel = new ReceiptCacheModel();

		receiptCacheModel.uuid = getUuid();

		String uuid = receiptCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			receiptCacheModel.uuid = null;
		}

		receiptCacheModel.receiptId = getReceiptId();

		receiptCacheModel.groupId = getGroupId();

		receiptCacheModel.companyId = getCompanyId();

		receiptCacheModel.userId = getUserId();

		receiptCacheModel.userName = getUserName();

		String userName = receiptCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			receiptCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			receiptCacheModel.createDate = createDate.getTime();
		}
		else {
			receiptCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			receiptCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			receiptCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		receiptCacheModel.typeId = getTypeId();

		receiptCacheModel.deliveryModeId = getDeliveryModeId();

		receiptCacheModel.receivedOn = getReceivedOn();

		String receivedOn = receiptCacheModel.receivedOn;

		if ((receivedOn != null) && (receivedOn.length() == 0)) {
			receiptCacheModel.receivedOn = null;
		}

		receiptCacheModel.letterDate = getLetterDate();

		String letterDate = receiptCacheModel.letterDate;

		if ((letterDate != null) && (letterDate.length() == 0)) {
			receiptCacheModel.letterDate = null;
		}

		receiptCacheModel.referenceNo = getReferenceNo();

		String referenceNo = receiptCacheModel.referenceNo;

		if ((referenceNo != null) && (referenceNo.length() == 0)) {
			receiptCacheModel.referenceNo = null;
		}

		receiptCacheModel.modeNo = getModeNo();

		String modeNo = receiptCacheModel.modeNo;

		if ((modeNo != null) && (modeNo.length() == 0)) {
			receiptCacheModel.modeNo = null;
		}

		receiptCacheModel.CategoryId = getCategoryId();

		receiptCacheModel.subject = getSubject();

		String subject = receiptCacheModel.subject;

		if ((subject != null) && (subject.length() == 0)) {
			receiptCacheModel.subject = null;
		}

		receiptCacheModel.remarks = getRemarks();

		String remarks = receiptCacheModel.remarks;

		if ((remarks != null) && (remarks.length() == 0)) {
			receiptCacheModel.remarks = null;
		}

		receiptCacheModel.name = getName();

		String name = receiptCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			receiptCacheModel.name = null;
		}

		receiptCacheModel.designation = getDesignation();

		String designation = receiptCacheModel.designation;

		if ((designation != null) && (designation.length() == 0)) {
			receiptCacheModel.designation = null;
		}

		receiptCacheModel.mobile = getMobile();

		String mobile = receiptCacheModel.mobile;

		if ((mobile != null) && (mobile.length() == 0)) {
			receiptCacheModel.mobile = null;
		}

		receiptCacheModel.email = getEmail();

		String email = receiptCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			receiptCacheModel.email = null;
		}

		receiptCacheModel.address = getAddress();

		String address = receiptCacheModel.address;

		if ((address != null) && (address.length() == 0)) {
			receiptCacheModel.address = null;
		}

		receiptCacheModel.stateId = getStateId();

		receiptCacheModel.pinCode = getPinCode();

		String pinCode = receiptCacheModel.pinCode;

		if ((pinCode != null) && (pinCode.length() == 0)) {
			receiptCacheModel.pinCode = null;
		}

		receiptCacheModel.receiptNo = getReceiptNo();

		String receiptNo = receiptCacheModel.receiptNo;

		if ((receiptNo != null) && (receiptNo.length() == 0)) {
			receiptCacheModel.receiptNo = null;
		}

		receiptCacheModel.organizationId = getOrganizationId();

		receiptCacheModel.city = getCity();

		String city = receiptCacheModel.city;

		if ((city != null) && (city.length() == 0)) {
			receiptCacheModel.city = null;
		}

		receiptCacheModel.userPostId = getUserPostId();

		receiptCacheModel.viewPdfUrl = getViewPdfUrl();

		String viewPdfUrl = receiptCacheModel.viewPdfUrl;

		if ((viewPdfUrl != null) && (viewPdfUrl.length() == 0)) {
			receiptCacheModel.viewPdfUrl = null;
		}

		receiptCacheModel.docFileId = getDocFileId();

		receiptCacheModel.nature = getNature();

		String nature = receiptCacheModel.nature;

		if ((nature != null) && (nature.length() == 0)) {
			receiptCacheModel.nature = null;
		}

		receiptCacheModel.currentlyWith = getCurrentlyWith();

		receiptCacheModel.currentState = getCurrentState();

		receiptCacheModel.attachStatus = getAttachStatus();

		String attachStatus = receiptCacheModel.attachStatus;

		if ((attachStatus != null) && (attachStatus.length() == 0)) {
			receiptCacheModel.attachStatus = null;
		}

		return receiptCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Receipt, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Receipt, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Receipt, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Receipt)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Receipt, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Receipt, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Receipt, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Receipt)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Receipt>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _receiptId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _typeId;
	private long _deliveryModeId;
	private String _receivedOn;
	private String _letterDate;
	private String _referenceNo;
	private String _modeNo;
	private long _CategoryId;
	private String _subject;
	private String _remarks;
	private String _name;
	private String _designation;
	private String _mobile;
	private String _email;
	private String _address;
	private long _stateId;
	private String _pinCode;
	private String _receiptNo;
	private long _organizationId;
	private String _city;
	private long _userPostId;
	private String _viewPdfUrl;
	private long _docFileId;
	private String _nature;
	private long _currentlyWith;
	private int _currentState;
	private String _attachStatus;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Receipt, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Receipt)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("receiptId", _receiptId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("typeId", _typeId);
		_columnOriginalValues.put("deliveryModeId", _deliveryModeId);
		_columnOriginalValues.put("receivedOn", _receivedOn);
		_columnOriginalValues.put("letterDate", _letterDate);
		_columnOriginalValues.put("referenceNo", _referenceNo);
		_columnOriginalValues.put("modeNo", _modeNo);
		_columnOriginalValues.put("CategoryId", _CategoryId);
		_columnOriginalValues.put("subject", _subject);
		_columnOriginalValues.put("remarks", _remarks);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("designation", _designation);
		_columnOriginalValues.put("mobile", _mobile);
		_columnOriginalValues.put("email", _email);
		_columnOriginalValues.put("address", _address);
		_columnOriginalValues.put("stateId", _stateId);
		_columnOriginalValues.put("pinCode", _pinCode);
		_columnOriginalValues.put("receiptNo", _receiptNo);
		_columnOriginalValues.put("organizationId", _organizationId);
		_columnOriginalValues.put("city", _city);
		_columnOriginalValues.put("userPostId", _userPostId);
		_columnOriginalValues.put("viewPdfUrl", _viewPdfUrl);
		_columnOriginalValues.put("docFileId", _docFileId);
		_columnOriginalValues.put("nature", _nature);
		_columnOriginalValues.put("currentlyWith", _currentlyWith);
		_columnOriginalValues.put("currentState", _currentState);
		_columnOriginalValues.put("attachStatus", _attachStatus);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("receiptId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("typeId", 256L);

		columnBitmasks.put("deliveryModeId", 512L);

		columnBitmasks.put("receivedOn", 1024L);

		columnBitmasks.put("letterDate", 2048L);

		columnBitmasks.put("referenceNo", 4096L);

		columnBitmasks.put("modeNo", 8192L);

		columnBitmasks.put("CategoryId", 16384L);

		columnBitmasks.put("subject", 32768L);

		columnBitmasks.put("remarks", 65536L);

		columnBitmasks.put("name", 131072L);

		columnBitmasks.put("designation", 262144L);

		columnBitmasks.put("mobile", 524288L);

		columnBitmasks.put("email", 1048576L);

		columnBitmasks.put("address", 2097152L);

		columnBitmasks.put("stateId", 4194304L);

		columnBitmasks.put("pinCode", 8388608L);

		columnBitmasks.put("receiptNo", 16777216L);

		columnBitmasks.put("organizationId", 33554432L);

		columnBitmasks.put("city", 67108864L);

		columnBitmasks.put("userPostId", 134217728L);

		columnBitmasks.put("viewPdfUrl", 268435456L);

		columnBitmasks.put("docFileId", 536870912L);

		columnBitmasks.put("nature", 1073741824L);

		columnBitmasks.put("currentlyWith", 2147483648L);

		columnBitmasks.put("currentState", 4294967296L);

		columnBitmasks.put("attachStatus", 8589934592L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Receipt _escapedModel;

}