/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package io.jetprocess.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import io.jetprocess.model.SecondaryHead;
import io.jetprocess.model.SecondaryHeadModel;
import io.jetprocess.model.SecondaryHeadSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SecondaryHead service. Represents a row in the &quot;JP_SecondaryHead&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SecondaryHeadModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SecondaryHeadImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SecondaryHeadImpl
 * @generated
 */
@JSON(strict = true)
public class SecondaryHeadModelImpl
	extends BaseModelImpl<SecondaryHead> implements SecondaryHeadModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a secondary head model instance should use the <code>SecondaryHead</code> interface instead.
	 */
	public static final String TABLE_NAME = "JP_SecondaryHead";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"secondaryHeadId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"secondaryHeadValue", Types.VARCHAR}, {"primaryHeadId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("secondaryHeadId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("secondaryHeadValue", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("primaryHeadId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table JP_SecondaryHead (uuid_ VARCHAR(75) null,secondaryHeadId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,secondaryHeadValue VARCHAR(75) null,primaryHeadId LONG)";

	public static final String TABLE_SQL_DROP = "drop table JP_SecondaryHead";

	public static final String ORDER_BY_JPQL =
		" ORDER BY secondaryHead.secondaryHeadId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY JP_SecondaryHead.secondaryHeadId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PRIMARYHEADID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SECONDARYHEADID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static SecondaryHead toModel(SecondaryHeadSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		SecondaryHead model = new SecondaryHeadImpl();

		model.setUuid(soapModel.getUuid());
		model.setSecondaryHeadId(soapModel.getSecondaryHeadId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setSecondaryHeadValue(soapModel.getSecondaryHeadValue());
		model.setPrimaryHeadId(soapModel.getPrimaryHeadId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<SecondaryHead> toModels(SecondaryHeadSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<SecondaryHead> models = new ArrayList<SecondaryHead>(
			soapModels.length);

		for (SecondaryHeadSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public SecondaryHeadModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _secondaryHeadId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSecondaryHeadId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _secondaryHeadId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SecondaryHead.class;
	}

	@Override
	public String getModelClassName() {
		return SecondaryHead.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SecondaryHead, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SecondaryHead, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SecondaryHead, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((SecondaryHead)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SecondaryHead, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SecondaryHead, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SecondaryHead)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SecondaryHead, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SecondaryHead, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, SecondaryHead>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			SecondaryHead.class.getClassLoader(), SecondaryHead.class,
			ModelWrapper.class);

		try {
			Constructor<SecondaryHead> constructor =
				(Constructor<SecondaryHead>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<SecondaryHead, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<SecondaryHead, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<SecondaryHead, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<SecondaryHead, Object>>();
		Map<String, BiConsumer<SecondaryHead, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<SecondaryHead, ?>>();

		attributeGetterFunctions.put("uuid", SecondaryHead::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<SecondaryHead, String>)SecondaryHead::setUuid);
		attributeGetterFunctions.put(
			"secondaryHeadId", SecondaryHead::getSecondaryHeadId);
		attributeSetterBiConsumers.put(
			"secondaryHeadId",
			(BiConsumer<SecondaryHead, Long>)SecondaryHead::setSecondaryHeadId);
		attributeGetterFunctions.put("groupId", SecondaryHead::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<SecondaryHead, Long>)SecondaryHead::setGroupId);
		attributeGetterFunctions.put("companyId", SecondaryHead::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<SecondaryHead, Long>)SecondaryHead::setCompanyId);
		attributeGetterFunctions.put("userId", SecondaryHead::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<SecondaryHead, Long>)SecondaryHead::setUserId);
		attributeGetterFunctions.put("userName", SecondaryHead::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<SecondaryHead, String>)SecondaryHead::setUserName);
		attributeGetterFunctions.put(
			"createDate", SecondaryHead::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<SecondaryHead, Date>)SecondaryHead::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", SecondaryHead::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<SecondaryHead, Date>)SecondaryHead::setModifiedDate);
		attributeGetterFunctions.put(
			"secondaryHeadValue", SecondaryHead::getSecondaryHeadValue);
		attributeSetterBiConsumers.put(
			"secondaryHeadValue",
			(BiConsumer<SecondaryHead, String>)
				SecondaryHead::setSecondaryHeadValue);
		attributeGetterFunctions.put(
			"primaryHeadId", SecondaryHead::getPrimaryHeadId);
		attributeSetterBiConsumers.put(
			"primaryHeadId",
			(BiConsumer<SecondaryHead, Long>)SecondaryHead::setPrimaryHeadId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getSecondaryHeadId() {
		return _secondaryHeadId;
	}

	@Override
	public void setSecondaryHeadId(long secondaryHeadId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_secondaryHeadId = secondaryHeadId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getSecondaryHeadValue() {
		if (_secondaryHeadValue == null) {
			return "";
		}
		else {
			return _secondaryHeadValue;
		}
	}

	@Override
	public void setSecondaryHeadValue(String secondaryHeadValue) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_secondaryHeadValue = secondaryHeadValue;
	}

	@JSON
	@Override
	public long getPrimaryHeadId() {
		return _primaryHeadId;
	}

	@Override
	public void setPrimaryHeadId(long primaryHeadId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_primaryHeadId = primaryHeadId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalPrimaryHeadId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("primaryHeadId"));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(SecondaryHead.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), SecondaryHead.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SecondaryHead toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SecondaryHead>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SecondaryHeadImpl secondaryHeadImpl = new SecondaryHeadImpl();

		secondaryHeadImpl.setUuid(getUuid());
		secondaryHeadImpl.setSecondaryHeadId(getSecondaryHeadId());
		secondaryHeadImpl.setGroupId(getGroupId());
		secondaryHeadImpl.setCompanyId(getCompanyId());
		secondaryHeadImpl.setUserId(getUserId());
		secondaryHeadImpl.setUserName(getUserName());
		secondaryHeadImpl.setCreateDate(getCreateDate());
		secondaryHeadImpl.setModifiedDate(getModifiedDate());
		secondaryHeadImpl.setSecondaryHeadValue(getSecondaryHeadValue());
		secondaryHeadImpl.setPrimaryHeadId(getPrimaryHeadId());

		secondaryHeadImpl.resetOriginalValues();

		return secondaryHeadImpl;
	}

	@Override
	public SecondaryHead cloneWithOriginalValues() {
		SecondaryHeadImpl secondaryHeadImpl = new SecondaryHeadImpl();

		secondaryHeadImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		secondaryHeadImpl.setSecondaryHeadId(
			this.<Long>getColumnOriginalValue("secondaryHeadId"));
		secondaryHeadImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		secondaryHeadImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		secondaryHeadImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		secondaryHeadImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		secondaryHeadImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		secondaryHeadImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		secondaryHeadImpl.setSecondaryHeadValue(
			this.<String>getColumnOriginalValue("secondaryHeadValue"));
		secondaryHeadImpl.setPrimaryHeadId(
			this.<Long>getColumnOriginalValue("primaryHeadId"));

		return secondaryHeadImpl;
	}

	@Override
	public int compareTo(SecondaryHead secondaryHead) {
		int value = 0;

		if (getSecondaryHeadId() < secondaryHead.getSecondaryHeadId()) {
			value = -1;
		}
		else if (getSecondaryHeadId() > secondaryHead.getSecondaryHeadId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SecondaryHead)) {
			return false;
		}

		SecondaryHead secondaryHead = (SecondaryHead)object;

		long primaryKey = secondaryHead.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SecondaryHead> toCacheModel() {
		SecondaryHeadCacheModel secondaryHeadCacheModel =
			new SecondaryHeadCacheModel();

		secondaryHeadCacheModel.uuid = getUuid();

		String uuid = secondaryHeadCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			secondaryHeadCacheModel.uuid = null;
		}

		secondaryHeadCacheModel.secondaryHeadId = getSecondaryHeadId();

		secondaryHeadCacheModel.groupId = getGroupId();

		secondaryHeadCacheModel.companyId = getCompanyId();

		secondaryHeadCacheModel.userId = getUserId();

		secondaryHeadCacheModel.userName = getUserName();

		String userName = secondaryHeadCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			secondaryHeadCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			secondaryHeadCacheModel.createDate = createDate.getTime();
		}
		else {
			secondaryHeadCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			secondaryHeadCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			secondaryHeadCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		secondaryHeadCacheModel.secondaryHeadValue = getSecondaryHeadValue();

		String secondaryHeadValue = secondaryHeadCacheModel.secondaryHeadValue;

		if ((secondaryHeadValue != null) &&
			(secondaryHeadValue.length() == 0)) {

			secondaryHeadCacheModel.secondaryHeadValue = null;
		}

		secondaryHeadCacheModel.primaryHeadId = getPrimaryHeadId();

		return secondaryHeadCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SecondaryHead, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SecondaryHead, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SecondaryHead, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((SecondaryHead)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<SecondaryHead, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<SecondaryHead, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SecondaryHead, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((SecondaryHead)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SecondaryHead>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _secondaryHeadId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _secondaryHeadValue;
	private long _primaryHeadId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<SecondaryHead, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((SecondaryHead)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("secondaryHeadId", _secondaryHeadId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("secondaryHeadValue", _secondaryHeadValue);
		_columnOriginalValues.put("primaryHeadId", _primaryHeadId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("secondaryHeadId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("secondaryHeadValue", 256L);

		columnBitmasks.put("primaryHeadId", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private SecondaryHead _escapedModel;

}