/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package io.jetprocess.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import io.jetprocess.model.TertiaryHead;
import io.jetprocess.model.TertiaryHeadModel;
import io.jetprocess.model.TertiaryHeadSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TertiaryHead service. Represents a row in the &quot;JP_TertiaryHead&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TertiaryHeadModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TertiaryHeadImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TertiaryHeadImpl
 * @generated
 */
@JSON(strict = true)
public class TertiaryHeadModelImpl
	extends BaseModelImpl<TertiaryHead> implements TertiaryHeadModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tertiary head model instance should use the <code>TertiaryHead</code> interface instead.
	 */
	public static final String TABLE_NAME = "JP_TertiaryHead";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"tertiaryHeadId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"tertiaryHeadvalue", Types.VARCHAR}, {"secondaryHeadId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("tertiaryHeadId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("tertiaryHeadvalue", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("secondaryHeadId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table JP_TertiaryHead (uuid_ VARCHAR(75) null,tertiaryHeadId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,tertiaryHeadvalue VARCHAR(75) null,secondaryHeadId LONG)";

	public static final String TABLE_SQL_DROP = "drop table JP_TertiaryHead";

	public static final String ORDER_BY_JPQL =
		" ORDER BY tertiaryHead.tertiaryHeadId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY JP_TertiaryHead.tertiaryHeadId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SECONDARYHEADID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TERTIARYHEADID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static TertiaryHead toModel(TertiaryHeadSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		TertiaryHead model = new TertiaryHeadImpl();

		model.setUuid(soapModel.getUuid());
		model.setTertiaryHeadId(soapModel.getTertiaryHeadId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setTertiaryHeadvalue(soapModel.getTertiaryHeadvalue());
		model.setSecondaryHeadId(soapModel.getSecondaryHeadId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<TertiaryHead> toModels(TertiaryHeadSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<TertiaryHead> models = new ArrayList<TertiaryHead>(
			soapModels.length);

		for (TertiaryHeadSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public TertiaryHeadModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _tertiaryHeadId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTertiaryHeadId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _tertiaryHeadId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TertiaryHead.class;
	}

	@Override
	public String getModelClassName() {
		return TertiaryHead.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TertiaryHead, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TertiaryHead, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TertiaryHead, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((TertiaryHead)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TertiaryHead, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TertiaryHead, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TertiaryHead)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TertiaryHead, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TertiaryHead, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, TertiaryHead>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			TertiaryHead.class.getClassLoader(), TertiaryHead.class,
			ModelWrapper.class);

		try {
			Constructor<TertiaryHead> constructor =
				(Constructor<TertiaryHead>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<TertiaryHead, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<TertiaryHead, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<TertiaryHead, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<TertiaryHead, Object>>();
		Map<String, BiConsumer<TertiaryHead, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<TertiaryHead, ?>>();

		attributeGetterFunctions.put("uuid", TertiaryHead::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<TertiaryHead, String>)TertiaryHead::setUuid);
		attributeGetterFunctions.put(
			"tertiaryHeadId", TertiaryHead::getTertiaryHeadId);
		attributeSetterBiConsumers.put(
			"tertiaryHeadId",
			(BiConsumer<TertiaryHead, Long>)TertiaryHead::setTertiaryHeadId);
		attributeGetterFunctions.put("groupId", TertiaryHead::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<TertiaryHead, Long>)TertiaryHead::setGroupId);
		attributeGetterFunctions.put("companyId", TertiaryHead::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<TertiaryHead, Long>)TertiaryHead::setCompanyId);
		attributeGetterFunctions.put("userId", TertiaryHead::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<TertiaryHead, Long>)TertiaryHead::setUserId);
		attributeGetterFunctions.put("userName", TertiaryHead::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<TertiaryHead, String>)TertiaryHead::setUserName);
		attributeGetterFunctions.put("createDate", TertiaryHead::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<TertiaryHead, Date>)TertiaryHead::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", TertiaryHead::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<TertiaryHead, Date>)TertiaryHead::setModifiedDate);
		attributeGetterFunctions.put(
			"tertiaryHeadvalue", TertiaryHead::getTertiaryHeadvalue);
		attributeSetterBiConsumers.put(
			"tertiaryHeadvalue",
			(BiConsumer<TertiaryHead, String>)
				TertiaryHead::setTertiaryHeadvalue);
		attributeGetterFunctions.put(
			"secondaryHeadId", TertiaryHead::getSecondaryHeadId);
		attributeSetterBiConsumers.put(
			"secondaryHeadId",
			(BiConsumer<TertiaryHead, Long>)TertiaryHead::setSecondaryHeadId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getTertiaryHeadId() {
		return _tertiaryHeadId;
	}

	@Override
	public void setTertiaryHeadId(long tertiaryHeadId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tertiaryHeadId = tertiaryHeadId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getTertiaryHeadvalue() {
		if (_tertiaryHeadvalue == null) {
			return "";
		}
		else {
			return _tertiaryHeadvalue;
		}
	}

	@Override
	public void setTertiaryHeadvalue(String tertiaryHeadvalue) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tertiaryHeadvalue = tertiaryHeadvalue;
	}

	@JSON
	@Override
	public long getSecondaryHeadId() {
		return _secondaryHeadId;
	}

	@Override
	public void setSecondaryHeadId(long secondaryHeadId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_secondaryHeadId = secondaryHeadId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalSecondaryHeadId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("secondaryHeadId"));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(TertiaryHead.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), TertiaryHead.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TertiaryHead toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TertiaryHead>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TertiaryHeadImpl tertiaryHeadImpl = new TertiaryHeadImpl();

		tertiaryHeadImpl.setUuid(getUuid());
		tertiaryHeadImpl.setTertiaryHeadId(getTertiaryHeadId());
		tertiaryHeadImpl.setGroupId(getGroupId());
		tertiaryHeadImpl.setCompanyId(getCompanyId());
		tertiaryHeadImpl.setUserId(getUserId());
		tertiaryHeadImpl.setUserName(getUserName());
		tertiaryHeadImpl.setCreateDate(getCreateDate());
		tertiaryHeadImpl.setModifiedDate(getModifiedDate());
		tertiaryHeadImpl.setTertiaryHeadvalue(getTertiaryHeadvalue());
		tertiaryHeadImpl.setSecondaryHeadId(getSecondaryHeadId());

		tertiaryHeadImpl.resetOriginalValues();

		return tertiaryHeadImpl;
	}

	@Override
	public TertiaryHead cloneWithOriginalValues() {
		TertiaryHeadImpl tertiaryHeadImpl = new TertiaryHeadImpl();

		tertiaryHeadImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		tertiaryHeadImpl.setTertiaryHeadId(
			this.<Long>getColumnOriginalValue("tertiaryHeadId"));
		tertiaryHeadImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		tertiaryHeadImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		tertiaryHeadImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		tertiaryHeadImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		tertiaryHeadImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		tertiaryHeadImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		tertiaryHeadImpl.setTertiaryHeadvalue(
			this.<String>getColumnOriginalValue("tertiaryHeadvalue"));
		tertiaryHeadImpl.setSecondaryHeadId(
			this.<Long>getColumnOriginalValue("secondaryHeadId"));

		return tertiaryHeadImpl;
	}

	@Override
	public int compareTo(TertiaryHead tertiaryHead) {
		int value = 0;

		if (getTertiaryHeadId() < tertiaryHead.getTertiaryHeadId()) {
			value = -1;
		}
		else if (getTertiaryHeadId() > tertiaryHead.getTertiaryHeadId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof TertiaryHead)) {
			return false;
		}

		TertiaryHead tertiaryHead = (TertiaryHead)object;

		long primaryKey = tertiaryHead.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<TertiaryHead> toCacheModel() {
		TertiaryHeadCacheModel tertiaryHeadCacheModel =
			new TertiaryHeadCacheModel();

		tertiaryHeadCacheModel.uuid = getUuid();

		String uuid = tertiaryHeadCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			tertiaryHeadCacheModel.uuid = null;
		}

		tertiaryHeadCacheModel.tertiaryHeadId = getTertiaryHeadId();

		tertiaryHeadCacheModel.groupId = getGroupId();

		tertiaryHeadCacheModel.companyId = getCompanyId();

		tertiaryHeadCacheModel.userId = getUserId();

		tertiaryHeadCacheModel.userName = getUserName();

		String userName = tertiaryHeadCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			tertiaryHeadCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			tertiaryHeadCacheModel.createDate = createDate.getTime();
		}
		else {
			tertiaryHeadCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			tertiaryHeadCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			tertiaryHeadCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		tertiaryHeadCacheModel.tertiaryHeadvalue = getTertiaryHeadvalue();

		String tertiaryHeadvalue = tertiaryHeadCacheModel.tertiaryHeadvalue;

		if ((tertiaryHeadvalue != null) && (tertiaryHeadvalue.length() == 0)) {
			tertiaryHeadCacheModel.tertiaryHeadvalue = null;
		}

		tertiaryHeadCacheModel.secondaryHeadId = getSecondaryHeadId();

		return tertiaryHeadCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TertiaryHead, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TertiaryHead, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TertiaryHead, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((TertiaryHead)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<TertiaryHead, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<TertiaryHead, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TertiaryHead, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((TertiaryHead)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, TertiaryHead>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _tertiaryHeadId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _tertiaryHeadvalue;
	private long _secondaryHeadId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<TertiaryHead, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((TertiaryHead)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("tertiaryHeadId", _tertiaryHeadId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("tertiaryHeadvalue", _tertiaryHeadvalue);
		_columnOriginalValues.put("secondaryHeadId", _secondaryHeadId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("tertiaryHeadId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("tertiaryHeadvalue", 256L);

		columnBitmasks.put("secondaryHeadId", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private TertiaryHead _escapedModel;

}