/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package io.jetprocess.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import io.jetprocess.model.TertiaryHead;
import io.jetprocess.model.TertiaryHeadModel;
import io.jetprocess.model.TertiaryHeadSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TertiaryHead service. Represents a row in the &quot;JP_TertiaryHead&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TertiaryHeadModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TertiaryHeadImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TertiaryHeadImpl
 * @generated
 */
@JSON(strict = true)
public class TertiaryHeadModelImpl
	extends BaseModelImpl<TertiaryHead> implements TertiaryHeadModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tertiary head model instance should use the <code>TertiaryHead</code> interface instead.
	 */
	public static final String TABLE_NAME = "JP_TertiaryHead";

	public static final Object[][] TABLE_COLUMNS = {
		{"tertiaryHeadId", Types.BIGINT}, {"tertiaryHeadvalue", Types.VARCHAR},
		{"secondaryHeadId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("tertiaryHeadId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("tertiaryHeadvalue", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("secondaryHeadId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table JP_TertiaryHead (tertiaryHeadId LONG not null primary key,tertiaryHeadvalue VARCHAR(75) null,secondaryHeadId LONG)";

	public static final String TABLE_SQL_DROP = "drop table JP_TertiaryHead";

	public static final String ORDER_BY_JPQL =
		" ORDER BY tertiaryHead.tertiaryHeadId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY JP_TertiaryHead.tertiaryHeadId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SECONDARYHEADID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TERTIARYHEADID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static TertiaryHead toModel(TertiaryHeadSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		TertiaryHead model = new TertiaryHeadImpl();

		model.setTertiaryHeadId(soapModel.getTertiaryHeadId());
		model.setTertiaryHeadvalue(soapModel.getTertiaryHeadvalue());
		model.setSecondaryHeadId(soapModel.getSecondaryHeadId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<TertiaryHead> toModels(TertiaryHeadSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<TertiaryHead> models = new ArrayList<TertiaryHead>(
			soapModels.length);

		for (TertiaryHeadSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public TertiaryHeadModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _tertiaryHeadId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTertiaryHeadId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _tertiaryHeadId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TertiaryHead.class;
	}

	@Override
	public String getModelClassName() {
		return TertiaryHead.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TertiaryHead, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TertiaryHead, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TertiaryHead, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((TertiaryHead)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TertiaryHead, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TertiaryHead, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TertiaryHead)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TertiaryHead, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TertiaryHead, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, TertiaryHead>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			TertiaryHead.class.getClassLoader(), TertiaryHead.class,
			ModelWrapper.class);

		try {
			Constructor<TertiaryHead> constructor =
				(Constructor<TertiaryHead>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<TertiaryHead, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<TertiaryHead, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<TertiaryHead, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<TertiaryHead, Object>>();
		Map<String, BiConsumer<TertiaryHead, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<TertiaryHead, ?>>();

		attributeGetterFunctions.put(
			"tertiaryHeadId", TertiaryHead::getTertiaryHeadId);
		attributeSetterBiConsumers.put(
			"tertiaryHeadId",
			(BiConsumer<TertiaryHead, Long>)TertiaryHead::setTertiaryHeadId);
		attributeGetterFunctions.put(
			"tertiaryHeadvalue", TertiaryHead::getTertiaryHeadvalue);
		attributeSetterBiConsumers.put(
			"tertiaryHeadvalue",
			(BiConsumer<TertiaryHead, String>)
				TertiaryHead::setTertiaryHeadvalue);
		attributeGetterFunctions.put(
			"secondaryHeadId", TertiaryHead::getSecondaryHeadId);
		attributeSetterBiConsumers.put(
			"secondaryHeadId",
			(BiConsumer<TertiaryHead, Long>)TertiaryHead::setSecondaryHeadId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getTertiaryHeadId() {
		return _tertiaryHeadId;
	}

	@Override
	public void setTertiaryHeadId(long tertiaryHeadId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tertiaryHeadId = tertiaryHeadId;
	}

	@JSON
	@Override
	public String getTertiaryHeadvalue() {
		if (_tertiaryHeadvalue == null) {
			return "";
		}
		else {
			return _tertiaryHeadvalue;
		}
	}

	@Override
	public void setTertiaryHeadvalue(String tertiaryHeadvalue) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tertiaryHeadvalue = tertiaryHeadvalue;
	}

	@JSON
	@Override
	public long getSecondaryHeadId() {
		return _secondaryHeadId;
	}

	@Override
	public void setSecondaryHeadId(long secondaryHeadId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_secondaryHeadId = secondaryHeadId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalSecondaryHeadId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("secondaryHeadId"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, TertiaryHead.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TertiaryHead toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TertiaryHead>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TertiaryHeadImpl tertiaryHeadImpl = new TertiaryHeadImpl();

		tertiaryHeadImpl.setTertiaryHeadId(getTertiaryHeadId());
		tertiaryHeadImpl.setTertiaryHeadvalue(getTertiaryHeadvalue());
		tertiaryHeadImpl.setSecondaryHeadId(getSecondaryHeadId());

		tertiaryHeadImpl.resetOriginalValues();

		return tertiaryHeadImpl;
	}

	@Override
	public TertiaryHead cloneWithOriginalValues() {
		TertiaryHeadImpl tertiaryHeadImpl = new TertiaryHeadImpl();

		tertiaryHeadImpl.setTertiaryHeadId(
			this.<Long>getColumnOriginalValue("tertiaryHeadId"));
		tertiaryHeadImpl.setTertiaryHeadvalue(
			this.<String>getColumnOriginalValue("tertiaryHeadvalue"));
		tertiaryHeadImpl.setSecondaryHeadId(
			this.<Long>getColumnOriginalValue("secondaryHeadId"));

		return tertiaryHeadImpl;
	}

	@Override
	public int compareTo(TertiaryHead tertiaryHead) {
		int value = 0;

		if (getTertiaryHeadId() < tertiaryHead.getTertiaryHeadId()) {
			value = -1;
		}
		else if (getTertiaryHeadId() > tertiaryHead.getTertiaryHeadId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof TertiaryHead)) {
			return false;
		}

		TertiaryHead tertiaryHead = (TertiaryHead)object;

		long primaryKey = tertiaryHead.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<TertiaryHead> toCacheModel() {
		TertiaryHeadCacheModel tertiaryHeadCacheModel =
			new TertiaryHeadCacheModel();

		tertiaryHeadCacheModel.tertiaryHeadId = getTertiaryHeadId();

		tertiaryHeadCacheModel.tertiaryHeadvalue = getTertiaryHeadvalue();

		String tertiaryHeadvalue = tertiaryHeadCacheModel.tertiaryHeadvalue;

		if ((tertiaryHeadvalue != null) && (tertiaryHeadvalue.length() == 0)) {
			tertiaryHeadCacheModel.tertiaryHeadvalue = null;
		}

		tertiaryHeadCacheModel.secondaryHeadId = getSecondaryHeadId();

		return tertiaryHeadCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TertiaryHead, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TertiaryHead, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TertiaryHead, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((TertiaryHead)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<TertiaryHead, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<TertiaryHead, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TertiaryHead, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((TertiaryHead)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, TertiaryHead>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _tertiaryHeadId;
	private String _tertiaryHeadvalue;
	private long _secondaryHeadId;

	public <T> T getColumnValue(String columnName) {
		Function<TertiaryHead, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((TertiaryHead)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("tertiaryHeadId", _tertiaryHeadId);
		_columnOriginalValues.put("tertiaryHeadvalue", _tertiaryHeadvalue);
		_columnOriginalValues.put("secondaryHeadId", _secondaryHeadId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("tertiaryHeadId", 1L);

		columnBitmasks.put("tertiaryHeadvalue", 2L);

		columnBitmasks.put("secondaryHeadId", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private TertiaryHead _escapedModel;

}